# Codacy configuration file
# Suppresses specific rules for package.json dependency version warnings
# These warnings are informational - package-lock.json locks exact versions

# Exclude paths from analysis
exclude_paths:
  - '**/node_modules/**'
  - '**/dist/**'
  - '**/build/**'

# Ignore assert statements in test files
# Assert statements are standard and expected in test files (pytest uses them extensively)
# Common assert-related patterns: Bandit B101, Pylint warnings
ignore_patterns:
  # Bandit B101: Use of assert detected (security warning that's acceptable in tests)
  - pattern_id: 'Bandit_B101'
    file_paths:
      - '**/test_*.py'
      - '**/tests/**/*.py'
      - '**/*_test.py'
  # Lizard CCN: Ignore cyclomatic complexity warnings for complexity <= 10
  # We want to only report complexity > 10, but Codacy doesn't support custom CCN thresholds
  # So we suppress the medium severity warnings (which report complexity > 8)
  # This effectively sets our threshold to 11 (only reports complexity > 10)
  - pattern_id: 'Lizard_ccn-medium'
    reason: 'Cyclomatic complexity threshold set to 11 (only report > 10). Medium severity reports > 8, which we want to ignore.'

# Cyclomatic complexity configuration
# Set cyclomatic complexity threshold to 11 (only report > 10)
# Since Codacy doesn't support custom CCN thresholds, we use ignore_patterns to suppress
# Lizard_ccn-medium (which reports complexity > 8), effectively setting threshold to 11
# Also configured in .codacy/codacy.yaml under engines.lizard.config.CCN (for CLI, if supported)
# Set file-nloc threshold to 550 (default is 500)
# Configured in .codacy/codacy.yaml under engines.lizard.config.file-nloc

# Engine-specific exclusions (alternative format that may work for CLI)
engines:
  lizard:
    exclude_patterns:
      - 'Lizard_ccn-medium'

# Line length configuration
# The project uses 120 character line length (not Codacy's default of 100)
# - Python: Configured via .pylintrc (max-line-length=120)
#   Enable "Use configuration file" for Pylint in Codacy's Code patterns page
# - TypeScript/JavaScript: Configured via client/eslint.config.js (max-len: 120)
#   Enable "Use configuration file" for ESLint in Codacy's Code patterns page

# Note: Package.json dependency version warnings cannot be suppressed via config file
# because JSON doesn't support comments. These warnings need to be suppressed via:
# 1. Codacy web interface (recommended)
# 2. Or by pinning exact versions (not recommended - breaks npm best practices)
#
# The warnings are about "Package dependencies with variant versions may lead to
# dependency hijack and confusion attacks" but these are false positives because:
# - Standard npm caret ranges (^) are used, which is best practice
# - package-lock.json locks exact versions at install time
# - No actual security risk exists when package-lock.json is committed
