# Codacy configuration file
# Suppresses specific rules for package.json dependency version warnings
# These warnings are informational - package-lock.json locks exact versions

# Exclude paths from analysis
exclude_paths:
  - '**/node_modules/**'
  - '**/dist/**'
  - '**/build/**'

# Note: Package.json dependency version warnings cannot be suppressed via config file
# because JSON doesn't support comments. These warnings need to be suppressed via:
# 1. Codacy web interface (recommended)
# 2. Or by pinning exact versions (not recommended - breaks npm best practices)
#
# The warnings are about "Package dependencies with variant versions may lead to
# dependency hijack and confusion attacks" but these are false positives because:
# - Standard npm caret ranges (^) are used, which is best practice
# - package-lock.json locks exact versions at install time
# - No actual security risk exists when package-lock.json is committed
