# Prometheus Configuration for MythosMUD Dual Connection System

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'mythos-cluster'
    environment: 'production'

rule_files:
  - "mythos_alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # MythosMUD Server Metrics
  - job_name: 'mythos-server'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 10s
    honor_labels: true

  # MythosMUD Health Endpoints
  - job_name: 'mythos-health'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/health'
    scrape_interval: 30s
    scrape_timeout: 10s

  # MythosMUD Connection Statistics
  - job_name: 'mythos-connections'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/monitoring/dual-connections'
    scrape_interval: 10s
    scrape_timeout: 5s

  # MythosMUD Performance Metrics
  - job_name: 'mythos-performance'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/monitoring/performance'
    scrape_interval: 15s
    scrape_timeout: 5s

  # MythosMUD Connection Health
  - job_name: 'mythos-connection-health'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/monitoring/connection-health'
    scrape_interval: 10s
    scrape_timeout: 5s

  # System Metrics (Node Exporter)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 15s

  # Database Metrics (if using PostgreSQL)
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['localhost:9187']
    scrape_interval: 30s

  # Redis Metrics (if using Redis)
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['localhost:9121']
    scrape_interval: 30s

# Remote write configuration for long-term storage
remote_write:
  - url: "http://localhost:8086/api/v1/prom/write"
    basic_auth:
      username: "prometheus"
      password: "your-password"
    queue_config:
      max_samples_per_send: 1000
      batch_send_deadline: 5s
      max_retries: 10
      min_backoff: 30ms
      max_backoff: 100ms

# Storage configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true
