[tool.poetry]
name = "mythosmud-server"
version = "0.1.0"
description = "Python FastAPI back-end for MythosMUD."
authors = ["Mark Henry <your-email@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.116.1"
uvicorn = "^0.29.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api" 