# MythosMUD Server Configuration - Unit Test Mode
# This configuration is used for pytest unit tests
# Secrets should be in .env.unit_test (not committed to git)

# --- Database & Persistence ---
db_path: ../data/unit_test/players/unit_test_players.db
npc_db_path: ../data/unit_test/npcs/unit_test_npcs.db

# --- Logging Configuration ---
logging:
  environment: unit_test
  level: DEBUG  # Full logging for test debugging
  format: json  # Structured logging for test analysis
  log_base: ./logs/  # Base logs directory, environment subdirectory added automatically
  rotation:
    max_size: 5MB
    backup_count: 2
  compression: false
  disable_logging: false

# --- Network ---
host: 127.0.0.1  # Localhost only for tests
port: 54732  # Different port to avoid conflicts with dev server
max_connections: 10  # Minimal for unit tests
connection_timeout: 30  # Shorter timeout for tests

# --- Dual Connection System ---
dual_connections:
  enabled: false  # Disabled for most unit tests
  max_connections_per_player: 1
  connection_timeout: 60
  health_check_interval: 10
  cleanup_interval: 30
  message_batch_size: 10
  connection_pool_size: 10
  performance_monitoring: false

  websocket:
    enabled: false
    ping_interval: 10
    ping_timeout: 5
    max_message_size: 1048576

  sse:
    enabled: false
    retry_timeout: 1000
    max_connections: 10

  session:
    timeout: 300  # 5 minutes for tests
    cleanup_interval: 60
    max_sessions_per_player: 2

  error_handling:
    max_retry_attempts: 1  # Minimal retries for fast test failures
    retry_delay: 1
    error_recovery_enabled: false  # Disabled for deterministic tests

  monitoring:
    enabled: false  # No monitoring in unit tests
    metrics_interval: 60
    health_check_interval: 30
    performance_tracking: false

# --- File Paths & Directories ---
data_dir: ../data/unit_test/
player_dir: ../data/unit_test/players/
log_dir: ./logs/
motd_file: ./data/unit_test/motd.html
aliases_dir: data/unit_test/players/aliases

# --- World & Game Settings ---
start_room: earth_arkhamcity_sanitarium_room_foyer_001
starting_level: 1
allow_multiplay: false  # Single-player for unit tests
max_players: 5  # Minimal for testing

# --- Modules/Systems ---
enable_combat: true
enable_weather: false  # Disabled for deterministic testing
enable_pvp: false

# --- Debug ---
enable_stack_traces: true

# --- Authentication/Accounts ---
auth_backend: sqlite
auth_db_file: ../data/unit_test/unit_unit_test_players.db
registration_enabled: true
allow_guest_login: false

# --- World Load/Boot Sequence ---
areas:
  - ./data/unit_test/rooms/arkham/
npcs:
  - ./data/unit_test/npcs/guards.json
quests: []  # Empty for tests unless specifically needed

# --- Room Validation ---
room_validation:
  enable_schema_validation: true
  strict_validation: false
  log_validation_errors: false  # Quieter test output

# --- Admin/Console/Telnet ---
admin_port: 5002  # Different port for tests
enable_remote_console: false

# --- Game Balance & Mechanics ---
xp_multiplier: 1.0
hp_regen_rate: 5
combat_tick_interval: 1  # Faster for tests

# --- NATS Configuration ---
nats:
  enabled: false  # Disabled for unit tests (enabled in integration tests)
  url: nats://localhost:4222
  max_payload: 1048576
  reconnect_time_wait: 1
  max_reconnect_attempts: 2  # Fewer retries for tests
  connect_timeout: 2
  ping_interval: 10
  max_outstanding_pings: 2

# --- Chat System Configuration ---
chat:
  rate_limiting:
    enabled: false  # Disabled for easier testing
    global: 100
    local: 100
    say: 100
    party: 100
    whisper: 100

  content_filtering:
    enabled: false  # Disabled for testing
    profanity_filter: false
    keyword_detection: false

  message_history:
    enabled: false  # Disabled for tests
    retention_days: 1
    max_messages_per_channel: 100

# --- Runtime/Scheduler ---
game_tick_rate: 0.1  # Faster game ticks for tests
weather_update_interval: 10
save_interval: 60

# --- Health Check Configuration ---
health_check:
  enabled: false  # Disabled for unit tests
  interval: 60
  timeout: 5
  retries: 1

# --- Backup Configuration ---
backup:
  enabled: false
  interval: 3600
  retention_days: 1
  path: ./logs/unit_test/backups

# --- Cache Configuration ---
cache:
  ttl: 60  # Short TTL for tests
  max_size: 10

# --- Monitoring & Alerting ---
monitoring:
  prometheus_enabled: false
  grafana_enabled: false
  alertmanager_enabled: false
  metrics_port: 9091
  email_alerts_enabled: false

# --- Feature Flags for Tests ---
features:
  enable_dual_connections: false  # Most unit tests don't need this
  enable_session_management: true
  enable_performance_monitoring: false
  enable_error_recovery: false
  enable_connection_health_checks: false
  enable_message_batching: false
  enable_connection_pooling: false
  enable_debug_endpoints: true
  enable_test_data: true
  enable_mock_services: true
  enable_development_tools: true
