-- MythosMUD Schema: Items and NPCs (static domains)
-- Static datasets will use deterministic v5 UUIDs generated by the loader.
-- This module defines item prototypes/components and NPC definitions/relationships/spawn rules.

SET client_min_messages = WARNING;
SET search_path = public;

-- Items: component states (e.g., durability tiers, status flags)
CREATE TABLE IF NOT EXISTS item_component_states (
    id              uuid PRIMARY KEY,
    stable_id       text NOT NULL UNIQUE,  -- e.g., 'condition_pristine'
    name            text NOT NULL,
    description     text,
    attributes      jsonb NOT NULL DEFAULT '{}'::jsonb
);

-- Items: prototypes
CREATE TABLE IF NOT EXISTS item_prototypes (
    id              uuid PRIMARY KEY,
    stable_id       text NOT NULL UNIQUE,  -- e.g., 'short_sword'
    name            text NOT NULL,
    description     text NOT NULL,
    category        text NOT NULL,         -- e.g., 'weapon', 'armor', 'consumable'
    rarity          text,                  -- free-text or consider enum later
    base_value      integer NOT NULL DEFAULT 0 CHECK (base_value >= 0),
    weight_grams    integer NOT NULL DEFAULT 0 CHECK (weight_grams >= 0),
    attributes      jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS idx_item_prototypes_category ON item_prototypes(category);
CREATE INDEX IF NOT EXISTS idx_item_prototypes_rarity ON item_prototypes(rarity);

-- Optional: mapping prototypes to default component states
CREATE TABLE IF NOT EXISTS item_prototype_component_defaults (
    item_id         uuid NOT NULL REFERENCES item_prototypes(id) ON DELETE CASCADE,
    component_state_id uuid NOT NULL REFERENCES item_component_states(id) ON DELETE RESTRICT,
    PRIMARY KEY (item_id, component_state_id)
);

-- NPCs: definitions
CREATE TABLE IF NOT EXISTS npc_definitions (
    id              uuid PRIMARY KEY,
    stable_id       text NOT NULL UNIQUE,  -- e.g., 'arkham_watch_guard'
    name            text NOT NULL,
    faction         text,
    profession_key  text,                  -- joins to professions.stable_id if relevant
    level           integer NOT NULL DEFAULT 1 CHECK (level >= 1),
    base_stats      jsonb NOT NULL DEFAULT '{}'::jsonb,
    attributes      jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS idx_npc_definitions_faction ON npc_definitions(faction);
CREATE INDEX IF NOT EXISTS idx_npc_definitions_profession ON npc_definitions(profession_key);

-- NPC relationships (free-text typed relationships)
CREATE TABLE IF NOT EXISTS npc_relationships (
    id              uuid PRIMARY KEY,
    from_npc_id     uuid NOT NULL REFERENCES npc_definitions(id) ON DELETE CASCADE,
    to_npc_id       uuid NOT NULL REFERENCES npc_definitions(id) ON DELETE RESTRICT,
    relation_type   text NOT NULL,         -- e.g., 'ally', 'enemy', 'mentor'
    strength        smallint NOT NULL DEFAULT 0, -- -100..100 perhaps; no check to keep flexible
    notes           text
);
CREATE INDEX IF NOT EXISTS idx_npc_relationships_from ON npc_relationships(from_npc_id);
CREATE INDEX IF NOT EXISTS idx_npc_relationships_to ON npc_relationships(to_npc_id);
CREATE INDEX IF NOT EXISTS idx_npc_relationships_type ON npc_relationships(relation_type);

-- NPC spawn rules (placement/schedule)
CREATE TABLE IF NOT EXISTS npc_spawn_rules (
    id              uuid PRIMARY KEY,
    npc_id          uuid NOT NULL REFERENCES npc_definitions(id) ON DELETE CASCADE,
    room_id         uuid REFERENCES rooms(id) ON DELETE SET NULL, -- optional: spawn location
    schedule_id     uuid REFERENCES calendar_npc_schedules(id) ON DELETE SET NULL,
    probability     numeric(5,4) NOT NULL DEFAULT 1.0000 CHECK (probability >= 0 AND probability <= 1),
    max_concurrent  smallint NOT NULL DEFAULT 1 CHECK (max_concurrent >= 0),
    attributes      jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS idx_npc_spawn_rules_npc ON npc_spawn_rules(npc_id);
CREATE INDEX IF NOT EXISTS idx_npc_spawn_rules_room ON npc_spawn_rules(room_id);
CREATE INDEX IF NOT EXISTS idx_npc_spawn_rules_schedule ON npc_spawn_rules(schedule_id);
