-- MythosMUD Schema: Items and NPCs (static domains)
-- Static datasets will use deterministic v5 UUIDs generated by the loader.
-- This module defines item prototypes/components and NPC definitions/relationships/spawn rules.
SET client_min_messages = WARNING;
SET search_path = public;
-- Items: component states (e.g., durability tiers, status flags)
-- NOTE: This is for STATIC component state definitions only
-- Runtime item_component_states table is created in 04_runtime_tables.sql
CREATE TABLE IF NOT EXISTS item_component_states_static (
    id uuid PRIMARY KEY,
    stable_id text NOT NULL UNIQUE,
    -- e.g., 'condition_pristine'
    name text NOT NULL,
    description text,
    attributes jsonb NOT NULL DEFAULT '{}'::jsonb
);
-- Items: prototypes
-- NOTE: Runtime item_prototypes table is created in 04_runtime_tables.sql
-- This static table is for reference data only
-- NOTE: Runtime NPC tables (npc_definitions, npc_spawn_rules, npc_relationships)
-- are created in 04_runtime_tables.sql to match the SQLAlchemy model.
-- This file is for static reference data only.
