-- Authoritative Database Schema
-- Generated from: mythos_dev database
-- Generated on: 2026-01-14 08:41:05 UTC
-- Generated by: scripts/generate_schema_from_dev.ps1
--
-- This file is the authoritative source of truth for the database schema.
-- It is generated directly from the mythos_dev database using pg_dump.
--
-- To regenerate this file:
--   1. Make schema changes in the mythos_dev database
--   2. Run: .\scripts\generate_schema_from_dev.ps1
--   3. Review the changes
--   4. Commit the updated file to git
--
-- SET statements for clean execution
SET client_min_messages = WARNING;
SET search_path = public;
--
-- PostgreSQL database dump
--

\restrict rW9Vr6fObqp4Mf84U62beFOvje4PFw1XOwgcF0EcaHsiLVaZX9K7vpXjBOkp8AB

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
-- transaction_timeout was introduced in PostgreSQL 17, but may not be recognized in all environments
-- Default value is 0 (disabled), so commenting out doesn't change behavior
-- SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.zone_configurations DROP CONSTRAINT IF EXISTS zone_configurations_zone_id_fkey;
ALTER TABLE IF EXISTS ONLY public.zone_configurations DROP CONSTRAINT IF EXISTS zone_configurations_subzone_id_fkey;
ALTER TABLE IF EXISTS ONLY public.subzones DROP CONSTRAINT IF EXISTS subzones_zone_id_fkey;
ALTER TABLE IF EXISTS ONLY public.rooms DROP CONSTRAINT IF EXISTS rooms_subzone_id_fkey;
ALTER TABLE IF EXISTS ONLY public.room_links DROP CONSTRAINT IF EXISTS room_links_to_room_id_fkey;
ALTER TABLE IF EXISTS ONLY public.room_links DROP CONSTRAINT IF EXISTS room_links_from_room_id_fkey;
ALTER TABLE IF EXISTS ONLY public.players DROP CONSTRAINT IF EXISTS players_new_user_id_fkey;
ALTER TABLE IF EXISTS ONLY public.player_spells DROP CONSTRAINT IF EXISTS player_spells_spell_id_fkey;
ALTER TABLE IF EXISTS ONLY public.player_spells DROP CONSTRAINT IF EXISTS player_spells_player_id_fkey;
ALTER TABLE IF EXISTS ONLY public.player_lucidity DROP CONSTRAINT IF EXISTS player_lucidity_player_id_fkey;
ALTER TABLE IF EXISTS ONLY public.player_inventories DROP CONSTRAINT IF EXISTS player_inventories_player_id_fkey;
ALTER TABLE IF EXISTS ONLY public.player_exploration DROP CONSTRAINT IF EXISTS player_exploration_room_id_fkey;
ALTER TABLE IF EXISTS ONLY public.player_exploration DROP CONSTRAINT IF EXISTS player_exploration_player_id_fkey;
ALTER TABLE IF EXISTS ONLY public.player_channel_preferences DROP CONSTRAINT IF EXISTS player_channel_preferences_player_id_fkey;
ALTER TABLE IF EXISTS ONLY public.npc_spawn_rules DROP CONSTRAINT IF EXISTS npc_spawn_rules_npc_definition_id_fkey;
ALTER TABLE IF EXISTS ONLY public.npc_relationships DROP CONSTRAINT IF EXISTS npc_relationships_npc_id_2_fkey;
ALTER TABLE IF EXISTS ONLY public.npc_relationships DROP CONSTRAINT IF EXISTS npc_relationships_npc_id_1_fkey;
ALTER TABLE IF EXISTS ONLY public.muting_rules DROP CONSTRAINT IF EXISTS muting_rules_created_by_user_fkey;
ALTER TABLE IF EXISTS ONLY public.lucidity_exposure_state DROP CONSTRAINT IF EXISTS lucidity_exposure_state_player_id_fkey;
ALTER TABLE IF EXISTS ONLY public.lucidity_cooldowns DROP CONSTRAINT IF EXISTS lucidity_cooldowns_player_id_fkey;
ALTER TABLE IF EXISTS ONLY public.lucidity_adjustment_log DROP CONSTRAINT IF EXISTS lucidity_adjustment_log_player_id_fkey;
ALTER TABLE IF EXISTS ONLY public.item_instances DROP CONSTRAINT IF EXISTS item_instances_prototype_id_fkey;
ALTER TABLE IF EXISTS ONLY public.item_component_states DROP CONSTRAINT IF EXISTS item_component_states_item_instance_id_fkey;
ALTER TABLE IF EXISTS ONLY public.invites DROP CONSTRAINT IF EXISTS invites_used_by_user_id_fkey;
ALTER TABLE IF EXISTS ONLY public.invites DROP CONSTRAINT IF EXISTS invites_created_by_user_fkey;
ALTER TABLE IF EXISTS ONLY public.id_map_players DROP CONSTRAINT IF EXISTS id_map_players_user_uuid_fkey;
ALTER TABLE IF EXISTS ONLY public.containers DROP CONSTRAINT IF EXISTS fk_containers_container_item_instance;
ALTER TABLE IF EXISTS ONLY public.emote_aliases DROP CONSTRAINT IF EXISTS emote_aliases_emote_id_fkey;
ALTER TABLE IF EXISTS ONLY public.containers DROP CONSTRAINT IF EXISTS containers_owner_id_fkey;
ALTER TABLE IF EXISTS ONLY public.containers DROP CONSTRAINT IF EXISTS containers_entity_id_fkey;
ALTER TABLE IF EXISTS ONLY public.container_contents DROP CONSTRAINT IF EXISTS container_contents_item_instance_id_fkey;
ALTER TABLE IF EXISTS ONLY public.container_contents DROP CONSTRAINT IF EXISTS container_contents_container_id_fkey;
DROP INDEX IF EXISTS public.uq_muting_active_per_target;
DROP INDEX IF EXISTS public.ix_containers_container_item_instance_id;
DROP INDEX IF EXISTS public.ix_container_contents_position;
DROP INDEX IF EXISTS public.ix_container_contents_item_instance_id;
DROP INDEX IF EXISTS public.ix_container_contents_container_id;
DROP INDEX IF EXISTS public.idx_zone_configs_zone;
DROP INDEX IF EXISTS public.idx_zone_configs_subzone;
DROP INDEX IF EXISTS public.idx_users_username_lower_unique;
DROP INDEX IF EXISTS public.idx_users_username;
DROP INDEX IF EXISTS public.idx_users_is_admin;
DROP INDEX IF EXISTS public.idx_users_email;
DROP INDEX IF EXISTS public.idx_subzones_zone;
DROP INDEX IF EXISTS public.idx_spells_school;
DROP INDEX IF EXISTS public.idx_spells_name;
DROP INDEX IF EXISTS public.idx_rooms_subzone;
DROP INDEX IF EXISTS public.idx_rooms_map_origin_zone;
DROP INDEX IF EXISTS public.idx_rooms_map_coordinates;
DROP INDEX IF EXISTS public.idx_room_links_to;
DROP INDEX IF EXISTS public.idx_room_links_from;
DROP INDEX IF EXISTS public.idx_professions_available;
DROP INDEX IF EXISTS public.idx_players_user_id_is_deleted;
DROP INDEX IF EXISTS public.idx_players_user_id;
DROP INDEX IF EXISTS public.idx_players_profession_id;
DROP INDEX IF EXISTS public.idx_players_name_lower_unique_active;
DROP INDEX IF EXISTS public.idx_players_name;
DROP INDEX IF EXISTS public.idx_players_is_admin;
DROP INDEX IF EXISTS public.idx_player_spells_spell_id;
DROP INDEX IF EXISTS public.idx_player_spells_player_id;
DROP INDEX IF EXISTS public.idx_player_lucidity_tier;
DROP INDEX IF EXISTS public.idx_player_inventories_player_id;
DROP INDEX IF EXISTS public.idx_player_exploration_room_id;
DROP INDEX IF EXISTS public.idx_player_exploration_player_id;
DROP INDEX IF EXISTS public.idx_player_exploration_explored_at;
DROP INDEX IF EXISTS public.idx_npc_spawn_rules_sub_zone;
DROP INDEX IF EXISTS public.idx_npc_spawn_rules_npc_def;
DROP INDEX IF EXISTS public.idx_npc_relationships_npc2;
DROP INDEX IF EXISTS public.idx_npc_relationships_npc1;
DROP INDEX IF EXISTS public.idx_npc_definitions_type;
DROP INDEX IF EXISTS public.idx_npc_definitions_sub_zone;
DROP INDEX IF EXISTS public.idx_npc_definitions_required;
DROP INDEX IF EXISTS public.idx_npc_definitions_name_sub_zone;
DROP INDEX IF EXISTS public.idx_npc_definitions_name;
DROP INDEX IF EXISTS public.idx_muting_expires_at;
DROP INDEX IF EXISTS public.idx_lucidity_exposure_player_id;
DROP INDEX IF EXISTS public.idx_lucidity_cooldowns_player_id;
DROP INDEX IF EXISTS public.idx_lucidity_adjustment_player_id;
DROP INDEX IF EXISTS public.idx_lucidity_adjustment_player_created;
DROP INDEX IF EXISTS public.idx_item_instances_prototype_id;
DROP INDEX IF EXISTS public.idx_item_instances_owner;
DROP INDEX IF EXISTS public.idx_item_component_states_instance_id;
DROP INDEX IF EXISTS public.idx_invites_used_by_user_id;
DROP INDEX IF EXISTS public.idx_invites_expires_at;
DROP INDEX IF EXISTS public.idx_invites_active;
DROP INDEX IF EXISTS public.idx_emote_alias_on_alias;
DROP INDEX IF EXISTS public.idx_containers_source_type;
DROP INDEX IF EXISTS public.idx_containers_room_id;
DROP INDEX IF EXISTS public.idx_containers_owner_id;
DROP INDEX IF EXISTS public.idx_containers_entity_id;
DROP INDEX IF EXISTS public.idx_containers_decay_at;
DROP INDEX IF EXISTS public.idx_calendar_npc_schedules_hours;
DROP INDEX IF EXISTS public.idx_calendar_npc_schedules_category;
DROP INDEX IF EXISTS public.idx_calendar_holidays_tradition;
DROP INDEX IF EXISTS public.idx_calendar_holidays_month_day;
DROP INDEX IF EXISTS public.idx_aliases_type_id;
ALTER TABLE IF EXISTS ONLY public.zones DROP CONSTRAINT IF EXISTS zones_stable_id_key;
ALTER TABLE IF EXISTS ONLY public.zones DROP CONSTRAINT IF EXISTS zones_pkey;
ALTER TABLE IF EXISTS ONLY public.zone_configurations DROP CONSTRAINT IF EXISTS zone_configurations_zone_id_subzone_id_key;
ALTER TABLE IF EXISTS ONLY public.zone_configurations DROP CONSTRAINT IF EXISTS zone_configurations_pkey;
ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT IF EXISTS users_pkey;
ALTER TABLE IF EXISTS ONLY public.subzones DROP CONSTRAINT IF EXISTS subzones_zone_id_stable_id_key;
ALTER TABLE IF EXISTS ONLY public.subzones DROP CONSTRAINT IF EXISTS subzones_pkey;
ALTER TABLE IF EXISTS ONLY public.spells DROP CONSTRAINT IF EXISTS spells_pkey;
ALTER TABLE IF EXISTS ONLY public.spells DROP CONSTRAINT IF EXISTS spells_name_key;
ALTER TABLE IF EXISTS ONLY public.rooms DROP CONSTRAINT IF EXISTS rooms_subzone_id_stable_id_key;
ALTER TABLE IF EXISTS ONLY public.rooms DROP CONSTRAINT IF EXISTS rooms_pkey;
ALTER TABLE IF EXISTS ONLY public.room_links DROP CONSTRAINT IF EXISTS room_links_pkey;
ALTER TABLE IF EXISTS ONLY public.room_links DROP CONSTRAINT IF EXISTS room_links_from_room_id_direction_key;
ALTER TABLE IF EXISTS ONLY public.professions DROP CONSTRAINT IF EXISTS professions_pkey;
ALTER TABLE IF EXISTS ONLY public.professions DROP CONSTRAINT IF EXISTS professions_name_key;
ALTER TABLE IF EXISTS ONLY public.players DROP CONSTRAINT IF EXISTS players_new_pkey;
ALTER TABLE IF EXISTS ONLY public.player_spells DROP CONSTRAINT IF EXISTS player_spells_player_id_spell_id_key;
ALTER TABLE IF EXISTS ONLY public.player_spells DROP CONSTRAINT IF EXISTS player_spells_pkey;
ALTER TABLE IF EXISTS ONLY public.player_lucidity DROP CONSTRAINT IF EXISTS player_lucidity_pkey;
ALTER TABLE IF EXISTS ONLY public.player_inventories DROP CONSTRAINT IF EXISTS player_inventories_pkey;
ALTER TABLE IF EXISTS ONLY public.player_exploration DROP CONSTRAINT IF EXISTS player_exploration_player_room_unique;
ALTER TABLE IF EXISTS ONLY public.player_exploration DROP CONSTRAINT IF EXISTS player_exploration_pkey;
ALTER TABLE IF EXISTS ONLY public.player_channel_preferences DROP CONSTRAINT IF EXISTS player_channel_preferences_pkey;
ALTER TABLE IF EXISTS ONLY public.npc_spawn_rules DROP CONSTRAINT IF EXISTS npc_spawn_rules_pkey;
ALTER TABLE IF EXISTS ONLY public.npc_relationships DROP CONSTRAINT IF EXISTS npc_relationships_pkey;
ALTER TABLE IF EXISTS ONLY public.npc_relationships DROP CONSTRAINT IF EXISTS npc_relationships_npc_id_1_npc_id_2_key;
ALTER TABLE IF EXISTS ONLY public.npc_definitions DROP CONSTRAINT IF EXISTS npc_definitions_pkey;
ALTER TABLE IF EXISTS ONLY public.muting_rules DROP CONSTRAINT IF EXISTS muting_rules_pkey;
ALTER TABLE IF EXISTS ONLY public.lucidity_exposure_state DROP CONSTRAINT IF EXISTS lucidity_exposure_state_player_id_entity_archetype_key;
ALTER TABLE IF EXISTS ONLY public.lucidity_exposure_state DROP CONSTRAINT IF EXISTS lucidity_exposure_state_pkey;
ALTER TABLE IF EXISTS ONLY public.lucidity_cooldowns DROP CONSTRAINT IF EXISTS lucidity_cooldowns_player_id_action_code_key;
ALTER TABLE IF EXISTS ONLY public.lucidity_cooldowns DROP CONSTRAINT IF EXISTS lucidity_cooldowns_pkey;
ALTER TABLE IF EXISTS ONLY public.lucidity_adjustment_log DROP CONSTRAINT IF EXISTS lucidity_adjustment_log_pkey;
ALTER TABLE IF EXISTS ONLY public.item_prototypes DROP CONSTRAINT IF EXISTS item_prototypes_pkey;
ALTER TABLE IF EXISTS ONLY public.item_instances DROP CONSTRAINT IF EXISTS item_instances_pkey;
ALTER TABLE IF EXISTS ONLY public.item_component_states DROP CONSTRAINT IF EXISTS item_component_states_pkey;
ALTER TABLE IF EXISTS ONLY public.item_component_states DROP CONSTRAINT IF EXISTS item_component_states_item_instance_id_component_id_key;
ALTER TABLE IF EXISTS ONLY public.invites DROP CONSTRAINT IF EXISTS invites_stable_id_key;
ALTER TABLE IF EXISTS ONLY public.invites DROP CONSTRAINT IF EXISTS invites_pkey;
ALTER TABLE IF EXISTS ONLY public.invites DROP CONSTRAINT IF EXISTS invites_code_key;
ALTER TABLE IF EXISTS ONLY public.id_map_users DROP CONSTRAINT IF EXISTS id_map_users_pkey;
ALTER TABLE IF EXISTS ONLY public.id_map_users DROP CONSTRAINT IF EXISTS id_map_users_new_uuid_key;
ALTER TABLE IF EXISTS ONLY public.id_map_players DROP CONSTRAINT IF EXISTS id_map_players_pkey;
ALTER TABLE IF EXISTS ONLY public.id_map_players DROP CONSTRAINT IF EXISTS id_map_players_new_uuid_key;
ALTER TABLE IF EXISTS ONLY public.emotes DROP CONSTRAINT IF EXISTS emotes_stable_id_key;
ALTER TABLE IF EXISTS ONLY public.emotes DROP CONSTRAINT IF EXISTS emotes_pkey;
ALTER TABLE IF EXISTS ONLY public.emote_aliases DROP CONSTRAINT IF EXISTS emote_aliases_pkey;
ALTER TABLE IF EXISTS ONLY public.containers DROP CONSTRAINT IF EXISTS containers_pkey;
ALTER TABLE IF EXISTS ONLY public.container_contents DROP CONSTRAINT IF EXISTS container_contents_pkey;
ALTER TABLE IF EXISTS ONLY public.calendar_npc_schedules DROP CONSTRAINT IF EXISTS calendar_npc_schedules_stable_id_key;
ALTER TABLE IF EXISTS ONLY public.calendar_npc_schedules DROP CONSTRAINT IF EXISTS calendar_npc_schedules_pkey;
ALTER TABLE IF EXISTS ONLY public.calendar_holidays DROP CONSTRAINT IF EXISTS calendar_holidays_stable_id_key;
ALTER TABLE IF EXISTS ONLY public.calendar_holidays DROP CONSTRAINT IF EXISTS calendar_holidays_pkey;
ALTER TABLE IF EXISTS ONLY public.aliases DROP CONSTRAINT IF EXISTS aliases_target_type_target_id_alias_key;
ALTER TABLE IF EXISTS ONLY public.aliases DROP CONSTRAINT IF EXISTS aliases_pkey;
DROP TABLE IF EXISTS public.zones;
DROP TABLE IF EXISTS public.zone_configurations;
DROP TABLE IF EXISTS public.users;
DROP TABLE IF EXISTS public.subzones;
DROP TABLE IF EXISTS public.spells;
DROP TABLE IF EXISTS public.rooms;
DROP TABLE IF EXISTS public.room_links;
DROP TABLE IF EXISTS public.professions;
DROP TABLE IF EXISTS public.players;
DROP TABLE IF EXISTS public.player_spells;
DROP TABLE IF EXISTS public.player_lucidity;
DROP TABLE IF EXISTS public.player_inventories;
DROP TABLE IF EXISTS public.player_exploration;
DROP TABLE IF EXISTS public.player_channel_preferences;
DROP TABLE IF EXISTS public.npc_spawn_rules;
DROP TABLE IF EXISTS public.npc_relationships;
DROP TABLE IF EXISTS public.npc_definitions;
DROP TABLE IF EXISTS public.muting_rules;
DROP TABLE IF EXISTS public.lucidity_exposure_state;
DROP TABLE IF EXISTS public.lucidity_cooldowns;
DROP TABLE IF EXISTS public.lucidity_adjustment_log;
DROP TABLE IF EXISTS public.item_prototypes;
DROP TABLE IF EXISTS public.item_instances;
DROP TABLE IF EXISTS public.item_component_states;
DROP TABLE IF EXISTS public.invites;
DROP TABLE IF EXISTS public.id_map_users;
DROP TABLE IF EXISTS public.id_map_players;
DROP TABLE IF EXISTS public.emotes;
DROP TABLE IF EXISTS public.emote_aliases;
DROP TABLE IF EXISTS public.containers;
DROP TABLE IF EXISTS public.container_contents;
DROP TABLE IF EXISTS public.calendar_npc_schedules;
DROP TABLE IF EXISTS public.calendar_holidays;
DROP TABLE IF EXISTS public.aliases;
DROP FUNCTION IF EXISTS public.remove_item_from_container(p_container_id uuid, p_item_instance_id character varying);
DROP FUNCTION IF EXISTS public.get_container_contents_json(p_container_id uuid);
DROP FUNCTION IF EXISTS public.clear_container_contents(p_container_id uuid);
DROP FUNCTION IF EXISTS public.add_item_to_container(p_container_id uuid, p_item_instance_id character varying, p_position integer);
DROP TYPE IF EXISTS public.season_enum;
DROP EXTENSION IF EXISTS pgcrypto;
--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


--
-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';


--
-- Name: season_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.season_enum AS ENUM (
    'winter',
    'spring',
    'summer',
    'autumn'
);


--
-- Name: add_item_to_container(uuid, character varying, integer); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.add_item_to_container(p_container_id uuid, p_item_instance_id character varying, p_position integer DEFAULT NULL::integer) RETURNS void
    LANGUAGE plpgsql
    AS $$
            DECLARE
                v_max_position INTEGER;
            BEGIN
                IF p_position IS NULL THEN
                    SELECT COALESCE(MAX(position), -1) + 1
                    INTO v_max_position
                    FROM container_contents
                    WHERE container_id = p_container_id;
                ELSE
                    v_max_position := p_position;
                END IF;

                INSERT INTO container_contents (container_id, item_instance_id, position)
                VALUES (p_container_id, p_item_instance_id, v_max_position)
                ON CONFLICT (container_id, item_instance_id)
                DO UPDATE SET position = v_max_position, updated_at = NOW();
            END;
            $$;


--
-- Name: clear_container_contents(uuid); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.clear_container_contents(p_container_id uuid) RETURNS integer
    LANGUAGE plpgsql
    AS $$
            DECLARE
                v_deleted INTEGER;
            BEGIN
                DELETE FROM container_contents
                WHERE container_id = p_container_id;

                GET DIAGNOSTICS v_deleted = ROW_COUNT;
                RETURN v_deleted;
            END;
            $$;


--
-- Name: get_container_contents_json(uuid); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.get_container_contents_json(p_container_id uuid) RETURNS jsonb
    LANGUAGE plpgsql
    AS $$
            DECLARE
                v_result JSONB;
            BEGIN
                SELECT COALESCE(
                    jsonb_agg(
                        jsonb_build_object(
                            'item_instance_id', cc.item_instance_id,
                            'item_id', ii.prototype_id,
                            'item_name', COALESCE(ii.custom_name, ip.name),
                            'quantity', ii.quantity,
                            'condition', ii.condition,
                            'metadata', ii.metadata,
                            'position', cc.position
                        )
                        ORDER BY cc.position
                    ),
                    '[]'::jsonb
                )
                INTO v_result
                FROM container_contents cc
                JOIN item_instances ii ON cc.item_instance_id = ii.item_instance_id
                JOIN item_prototypes ip ON ii.prototype_id = ip.prototype_id
                WHERE cc.container_id = p_container_id;

                RETURN v_result;
            END;
            $$;


--
-- Name: remove_item_from_container(uuid, character varying); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.remove_item_from_container(p_container_id uuid, p_item_instance_id character varying) RETURNS boolean
    LANGUAGE plpgsql
    AS $$
            DECLARE
                v_deleted INTEGER;
            BEGIN
                DELETE FROM container_contents
                WHERE container_id = p_container_id
                  AND item_instance_id = p_item_instance_id;

                GET DIAGNOSTICS v_deleted = ROW_COUNT;
                RETURN v_deleted > 0;
            END;
            $$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: aliases; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.aliases (
    id uuid NOT NULL,
    target_type text NOT NULL,
    target_id uuid NOT NULL,
    alias text NOT NULL
);


--
-- Name: calendar_holidays; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.calendar_holidays (
    id uuid NOT NULL,
    stable_id text NOT NULL,
    name text NOT NULL,
    tradition text NOT NULL,
    month smallint NOT NULL,
    day smallint NOT NULL,
    duration_hours smallint NOT NULL,
    season public.season_enum NOT NULL,
    bonus_tags text[] DEFAULT '{}'::text[] NOT NULL,
    CONSTRAINT calendar_holidays_day_check CHECK (((day >= 1) AND (day <= 31))),
    CONSTRAINT calendar_holidays_duration_hours_check CHECK (((duration_hours >= 1) AND (duration_hours <= 168))),
    CONSTRAINT calendar_holidays_month_check CHECK (((month >= 1) AND (month <= 12)))
);


--
-- Name: calendar_npc_schedules; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.calendar_npc_schedules (
    id uuid NOT NULL,
    stable_id text NOT NULL,
    name text NOT NULL,
    category text NOT NULL,
    start_hour smallint NOT NULL,
    end_hour smallint NOT NULL,
    days text[] NOT NULL,
    applies_to text[] NOT NULL,
    effects text[] NOT NULL,
    notes text,
    CONSTRAINT calendar_npc_schedules_end_hour_check CHECK (((end_hour >= 0) AND (end_hour <= 24))),
    CONSTRAINT calendar_npc_schedules_start_hour_check CHECK (((start_hour >= 0) AND (start_hour <= 24)))
);


--
-- Name: container_contents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.container_contents (
    container_id uuid NOT NULL,
    item_instance_id character varying(64) NOT NULL,
    "position" integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: containers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.containers (
    container_instance_id uuid DEFAULT gen_random_uuid() NOT NULL,
    source_type text NOT NULL,
    owner_id uuid,
    room_id character varying(255),
    entity_id uuid,
    lock_state text DEFAULT 'unlocked'::text NOT NULL,
    capacity_slots integer NOT NULL,
    weight_limit integer,
    decay_at timestamp with time zone,
    allowed_roles jsonb,
    metadata_json jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    container_item_instance_id character varying(64),
    items_json jsonb DEFAULT '[]'::jsonb NOT NULL,
    CONSTRAINT containers_capacity_slots_check CHECK (((capacity_slots > 0) AND (capacity_slots <= 20))),
    CONSTRAINT containers_lock_state_check CHECK ((lock_state = ANY (ARRAY['unlocked'::text, 'locked'::text, 'sealed'::text]))),
    CONSTRAINT containers_source_type_check CHECK ((source_type = ANY (ARRAY['environment'::text, 'equipment'::text, 'corpse'::text]))),
    CONSTRAINT containers_weight_limit_check CHECK (((weight_limit IS NULL) OR (weight_limit > 0)))
);


--
-- Name: TABLE containers; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.containers IS 'Unified container system for environmental props, wearable gear, and corpses';


--
-- Name: COLUMN containers.container_instance_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.containers.container_instance_id IS 'Unique identifier for container instance';


--
-- Name: COLUMN containers.source_type; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.containers.source_type IS 'Type of container: environment (room objects), equipment (wearable), or corpse';


--
-- Name: COLUMN containers.owner_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.containers.owner_id IS 'UUID of player/NPC who owns the container (NULL for shared environmental containers)';


--
-- Name: COLUMN containers.room_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.containers.room_id IS 'Room identifier for environmental and corpse containers';


--
-- Name: COLUMN containers.entity_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.containers.entity_id IS 'Player/NPC UUID when container is wearable equipment';


--
-- Name: COLUMN containers.lock_state; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.containers.lock_state IS 'Lock state: unlocked, locked, or sealed';


--
-- Name: COLUMN containers.capacity_slots; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.containers.capacity_slots IS 'Maximum number of inventory slots (1-20)';


--
-- Name: COLUMN containers.weight_limit; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.containers.weight_limit IS 'Optional maximum weight capacity';


--
-- Name: COLUMN containers.decay_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.containers.decay_at IS 'Timestamp when corpse container should decay and be cleaned up';


--
-- Name: COLUMN containers.allowed_roles; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.containers.allowed_roles IS 'JSONB array of role names allowed to access container';


--
-- Name: COLUMN containers.metadata_json; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.containers.metadata_json IS 'Optional JSONB metadata for container-specific configuration';


--
-- Name: COLUMN containers.items_json; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.containers.items_json IS 'JSONB array of InventoryStack items stored in container';


--
-- Name: emote_aliases; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.emote_aliases (
    emote_id uuid NOT NULL,
    alias text NOT NULL
);


--
-- Name: emotes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.emotes (
    id uuid NOT NULL,
    stable_id text NOT NULL,
    self_message text NOT NULL,
    other_message text NOT NULL
);


--
-- Name: id_map_players; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.id_map_players (
    old_sqlite_id text NOT NULL,
    new_uuid uuid NOT NULL,
    user_uuid uuid NOT NULL,
    name text
);


--
-- Name: id_map_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.id_map_users (
    old_sqlite_id text NOT NULL,
    new_uuid uuid NOT NULL,
    username text
);


--
-- Name: invites; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.invites (
    id uuid NOT NULL,
    stable_id text,
    invite_code text CONSTRAINT invites_code_not_null NOT NULL,
    description text,
    created_by_user_id uuid,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone,
    used_by_user_id uuid
);


--
-- Name: TABLE invites; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.invites IS 'Manages invite-only registration system with expiration tracking.';


--
-- Name: item_component_states; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.item_component_states (
    id bigint NOT NULL,
    item_instance_id character varying(64) NOT NULL,
    component_id character varying(120) NOT NULL,
    state_payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE item_component_states; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.item_component_states IS 'Component-specific state data for item instances.';


--
-- Name: item_component_states_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.item_component_states ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.item_component_states_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: item_instances; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.item_instances (
    item_instance_id character varying(64) NOT NULL,
    prototype_id character varying(120) NOT NULL,
    owner_type character varying(32) DEFAULT 'room'::character varying NOT NULL,
    owner_id character varying(255),
    location_context character varying(255),
    quantity integer DEFAULT 1 NOT NULL,
    condition integer,
    flags_override jsonb DEFAULT '[]'::jsonb NOT NULL,
    binding_state character varying(32),
    attunement_state jsonb DEFAULT '{}'::jsonb NOT NULL,
    custom_name character varying(255),
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    origin_source character varying(64),
    origin_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE item_instances; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.item_instances IS 'Runtime instances of items in the game world.';


--
-- Name: item_prototypes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.item_prototypes (
    prototype_id character varying(120) NOT NULL,
    name character varying(120) NOT NULL,
    short_description character varying(255) NOT NULL,
    long_description text NOT NULL,
    item_type character varying(32) NOT NULL,
    weight double precision DEFAULT 0.0 NOT NULL,
    base_value integer DEFAULT 0 NOT NULL,
    durability integer,
    flags jsonb DEFAULT '[]'::jsonb NOT NULL,
    wear_slots jsonb DEFAULT '[]'::jsonb NOT NULL,
    stacking_rules jsonb DEFAULT '{}'::jsonb NOT NULL,
    usage_restrictions jsonb DEFAULT '{}'::jsonb NOT NULL,
    effect_components jsonb DEFAULT '[]'::jsonb NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    tags jsonb DEFAULT '[]'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE item_prototypes; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.item_prototypes IS 'Static reference data for item types and their properties.';


--
-- Name: lucidity_adjustment_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lucidity_adjustment_log (
    id bigint CONSTRAINT sanity_adjustment_log_id_not_null NOT NULL,
    player_id uuid CONSTRAINT sanity_adjustment_log_player_id_not_null NOT NULL,
    delta integer CONSTRAINT sanity_adjustment_log_delta_not_null NOT NULL,
    reason_code text CONSTRAINT sanity_adjustment_log_reason_code_not_null NOT NULL,
    metadata text DEFAULT '{}'::text CONSTRAINT sanity_adjustment_log_metadata_not_null NOT NULL,
    location_id character varying(255),
    created_at timestamp with time zone DEFAULT now() CONSTRAINT sanity_adjustment_log_created_at_not_null NOT NULL
);


--
-- Name: TABLE lucidity_adjustment_log; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.lucidity_adjustment_log IS 'Immutable ledger for every lucidity gain or loss event.';


--
-- Name: COLUMN lucidity_adjustment_log.delta; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.lucidity_adjustment_log.delta IS 'Change in lucidity value (positive for gain, negative for loss).';


--
-- Name: COLUMN lucidity_adjustment_log.reason_code; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.lucidity_adjustment_log.reason_code IS 'Code identifying the reason for the lucidity adjustment.';


--
-- Name: lucidity_adjustment_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.lucidity_adjustment_log ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.lucidity_adjustment_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lucidity_cooldowns; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lucidity_cooldowns (
    id bigint CONSTRAINT sanity_cooldowns_id_not_null NOT NULL,
    player_id uuid CONSTRAINT sanity_cooldowns_player_id_not_null NOT NULL,
    action_code text CONSTRAINT sanity_cooldowns_action_code_not_null NOT NULL,
    cooldown_expires_at timestamp with time zone CONSTRAINT sanity_cooldowns_cooldown_expires_at_not_null NOT NULL
);


--
-- Name: TABLE lucidity_cooldowns; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.lucidity_cooldowns IS 'Cooldown tracker for recovery rituals and hallucination timers.';


--
-- Name: lucidity_cooldowns_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.lucidity_cooldowns ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.lucidity_cooldowns_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lucidity_exposure_state; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lucidity_exposure_state (
    id bigint CONSTRAINT sanity_exposure_state_id_not_null NOT NULL,
    player_id uuid CONSTRAINT sanity_exposure_state_player_id_not_null NOT NULL,
    entity_archetype text CONSTRAINT sanity_exposure_state_entity_archetype_not_null NOT NULL,
    encounter_count integer DEFAULT 0 CONSTRAINT sanity_exposure_state_encounter_count_not_null NOT NULL,
    last_encounter_at timestamp with time zone DEFAULT now() CONSTRAINT sanity_exposure_state_last_encounter_at_not_null NOT NULL
);


--
-- Name: TABLE lucidity_exposure_state; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.lucidity_exposure_state IS 'Tracks repeated exposure to particular eldritch archetypes.';


--
-- Name: lucidity_exposure_state_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.lucidity_exposure_state ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.lucidity_exposure_state_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: muting_rules; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.muting_rules (
    id uuid NOT NULL,
    target_type text NOT NULL,
    target_id uuid NOT NULL,
    reason text,
    created_by_user uuid,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone
);


--
-- Name: TABLE muting_rules; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.muting_rules IS 'Admin moderation rules for muting users or players.';


--
-- Name: npc_definitions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.npc_definitions (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    npc_type character varying(20) NOT NULL,
    sub_zone_id character varying(50) NOT NULL,
    room_id character varying(50),
    required_npc boolean DEFAULT false NOT NULL,
    max_population integer DEFAULT 1 NOT NULL,
    spawn_probability real DEFAULT 1.0 NOT NULL,
    base_stats text DEFAULT '{}'::text NOT NULL,
    behavior_config text DEFAULT '{}'::text NOT NULL,
    ai_integration_stub text DEFAULT '{}'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT npc_definitions_npc_type_check CHECK (((npc_type)::text = ANY ((ARRAY['shopkeeper'::character varying, 'quest_giver'::character varying, 'passive_mob'::character varying, 'aggressive_mob'::character varying])::text[])))
);


--
-- Name: TABLE npc_definitions; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.npc_definitions IS 'Static reference data for NPC types and their configurations.';


--
-- Name: npc_definitions_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.npc_definitions ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.npc_definitions_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: npc_relationships; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.npc_relationships (
    id bigint NOT NULL,
    npc_id_1 bigint NOT NULL,
    npc_id_2 bigint NOT NULL,
    relationship_type character varying(20) NOT NULL,
    relationship_strength real DEFAULT 0.5,
    CONSTRAINT npc_relationships_relationship_type_check CHECK (((relationship_type)::text = ANY ((ARRAY['ally'::character varying, 'enemy'::character varying, 'neutral'::character varying, 'follower'::character varying])::text[])))
);


--
-- Name: TABLE npc_relationships; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.npc_relationships IS 'Relationship mappings between NPCs (ally, enemy, neutral, follower).';


--
-- Name: npc_relationships_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.npc_relationships ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.npc_relationships_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: npc_spawn_rules; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.npc_spawn_rules (
    id bigint NOT NULL,
    npc_definition_id bigint NOT NULL,
    sub_zone_id character varying(50) NOT NULL,
    min_population integer DEFAULT 0,
    max_population integer DEFAULT 999,
    spawn_conditions text DEFAULT '{}'::text NOT NULL
);


--
-- Name: TABLE npc_spawn_rules; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.npc_spawn_rules IS 'Rules governing NPC spawning behavior in subzones.';


--
-- Name: npc_spawn_rules_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.npc_spawn_rules ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.npc_spawn_rules_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: player_channel_preferences; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.player_channel_preferences (
    player_id uuid NOT NULL,
    default_channel character varying(32) NOT NULL,
    muted_channels jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: player_exploration; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.player_exploration (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    player_id uuid NOT NULL,
    room_id uuid NOT NULL,
    explored_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE player_exploration; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.player_exploration IS 'Junction table tracking which rooms each player has explored. Used for map visibility filtering.';


--
-- Name: COLUMN player_exploration.id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.player_exploration.id IS 'Primary key (UUID)';


--
-- Name: COLUMN player_exploration.player_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.player_exploration.player_id IS 'Foreign key to players table';


--
-- Name: COLUMN player_exploration.room_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.player_exploration.room_id IS 'Foreign key to rooms table';


--
-- Name: COLUMN player_exploration.explored_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.player_exploration.explored_at IS 'Timestamp when the room was first explored by the player';


--
-- Name: player_inventories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.player_inventories (
    player_id uuid NOT NULL,
    inventory_json text DEFAULT '[]'::text NOT NULL,
    equipped_json text DEFAULT '{}'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE player_inventories; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.player_inventories IS 'Stores JSON payloads for player inventory and equipped items.';


--
-- Name: player_lucidity; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.player_lucidity (
    player_id uuid CONSTRAINT player_sanity_player_id_not_null NOT NULL,
    current_lcd integer DEFAULT 100 CONSTRAINT player_sanity_current_san_not_null NOT NULL,
    current_tier character varying(32) DEFAULT 'lucid'::character varying CONSTRAINT player_sanity_current_tier_not_null NOT NULL,
    liabilities text DEFAULT '[]'::text CONSTRAINT player_sanity_liabilities_not_null NOT NULL,
    last_updated_at timestamp with time zone DEFAULT now() CONSTRAINT player_sanity_last_updated_at_not_null NOT NULL,
    catatonia_entered_at timestamp with time zone,
    CONSTRAINT player_lucidity_current_lcd_check CHECK (((current_lcd >= '-100'::integer) AND (current_lcd <= 100))),
    CONSTRAINT player_lucidity_current_tier_check CHECK (((current_tier)::text = ANY ((ARRAY['lucid'::character varying, 'uneasy'::character varying, 'fractured'::character varying, 'deranged'::character varying, 'catatonic'::character varying])::text[])))
);


--
-- Name: TABLE player_lucidity; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.player_lucidity IS 'Tracks player lucidity (sanity) state and tier.';


--
-- Name: COLUMN player_lucidity.current_lcd; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.player_lucidity.current_lcd IS 'Current lucidity value (-100 to +100).';


--
-- Name: COLUMN player_lucidity.current_tier; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.player_lucidity.current_tier IS 'Current lucidity tier: lucid, uneasy, fractured, deranged, or catatonic.';


--
-- Name: player_spells; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.player_spells (
    id bigint NOT NULL,
    player_id uuid NOT NULL,
    spell_id character varying(255) NOT NULL,
    mastery integer DEFAULT 0 NOT NULL,
    learned_at timestamp with time zone DEFAULT now() NOT NULL,
    last_cast_at timestamp with time zone,
    times_cast integer DEFAULT 0 NOT NULL,
    CONSTRAINT player_spells_mastery_check CHECK (((mastery >= 0) AND (mastery <= 100)))
);


--
-- Name: TABLE player_spells; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.player_spells IS 'Tracks spells learned by players and their mastery levels.';


--
-- Name: player_spells_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.player_spells ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.player_spells_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: players; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.players (
    player_id uuid CONSTRAINT players_new_player_id_not_null NOT NULL,
    user_id uuid CONSTRAINT players_new_user_id_not_null NOT NULL,
    name character varying(50) CONSTRAINT players_new_name_not_null NOT NULL,
    inventory text DEFAULT '[]'::text CONSTRAINT players_new_inventory_not_null NOT NULL,
    status_effects text DEFAULT '[]'::text CONSTRAINT players_new_status_effects_not_null NOT NULL,
    current_room_id character varying(255) DEFAULT 'earth_arkhamcity_sanitarium_room_foyer_001'::character varying CONSTRAINT players_new_current_room_id_not_null NOT NULL,
    respawn_room_id character varying(100) DEFAULT 'earth_arkhamcity_sanitarium_room_foyer_001'::character varying,
    experience_points integer DEFAULT 0 CONSTRAINT players_new_experience_points_not_null NOT NULL,
    level integer DEFAULT 1 CONSTRAINT players_new_level_not_null NOT NULL,
    is_admin integer DEFAULT 0 CONSTRAINT players_new_is_admin_not_null NOT NULL,
    profession_id bigint,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT players_new_created_at_not_null NOT NULL,
    last_active timestamp with time zone DEFAULT now() CONSTRAINT players_new_last_active_not_null NOT NULL,
    stats jsonb DEFAULT '{"luck": 50, "size": 50, "power": 50, "occult": 0, "charisma": 50, "lucidity": 100, "position": "standing", "strength": 50, "dexterity": 50, "education": 50, "corruption": 0, "current_dp": 20, "constitution": 50, "intelligence": 50, "magic_points": 10}'::jsonb CONSTRAINT players_stats_jsonb_not_null NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamp with time zone
);


--
-- Name: TABLE players; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.players IS 'Stores runtime game data for player characters.';


--
-- Name: COLUMN players.player_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.players.player_id IS 'Primary key: Unique identifier for the player character.';


--
-- Name: COLUMN players.user_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.players.user_id IS 'Foreign key to users table. Links player to user account.';


--
-- Name: COLUMN players.name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.players.name IS 'Character name (must be unique, case-sensitive).';


--
-- Name: COLUMN players.inventory; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.players.inventory IS 'JSON array of inventory items.';


--
-- Name: COLUMN players.status_effects; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.players.status_effects IS 'JSON array of active status effects.';


--
-- Name: COLUMN players.stats; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.players.stats IS 'JSON object containing character statistics (strength, dexterity, etc.).';


--
-- Name: COLUMN players.is_deleted; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.players.is_deleted IS 'Soft delete flag - deleted characters are hidden but not removed from database';


--
-- Name: COLUMN players.deleted_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.players.deleted_at IS 'Timestamp when character was soft-deleted (NULL for active characters)';


--
-- Name: professions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.professions (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    description text NOT NULL,
    flavor_text text NOT NULL,
    stat_requirements text DEFAULT '{}'::text NOT NULL,
    mechanical_effects text DEFAULT '{}'::text NOT NULL,
    is_available boolean DEFAULT true NOT NULL
);


--
-- Name: TABLE professions; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.professions IS 'Static reference data for character professions and their requirements.';


--
-- Name: COLUMN professions.id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.professions.id IS 'Primary key: bigint generated always as identity.';


--
-- Name: COLUMN professions.name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.professions.name IS 'Profession name (must be unique).';


--
-- Name: COLUMN professions.stat_requirements; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.professions.stat_requirements IS 'JSON object defining minimum stat requirements for the profession.';


--
-- Name: COLUMN professions.mechanical_effects; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.professions.mechanical_effects IS 'JSON object defining mechanical bonuses/penalties for the profession.';


--
-- Name: professions_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.professions ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.professions_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: room_links; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.room_links (
    id uuid NOT NULL,
    from_room_id uuid NOT NULL,
    to_room_id uuid NOT NULL,
    direction text NOT NULL,
    attributes jsonb DEFAULT '{}'::jsonb NOT NULL
);


--
-- Name: rooms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rooms (
    id uuid NOT NULL,
    subzone_id uuid NOT NULL,
    stable_id text NOT NULL,
    name text NOT NULL,
    description text NOT NULL,
    attributes jsonb DEFAULT '{}'::jsonb NOT NULL,
    map_x numeric(10,2),
    map_y numeric(10,2),
    map_origin_zone boolean DEFAULT false NOT NULL,
    map_symbol text,
    map_style text
);


--
-- Name: COLUMN rooms.map_x; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.rooms.map_x IS 'X coordinate for room position on the interactive map (admin layout). NULL if not set.';


--
-- Name: COLUMN rooms.map_y; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.rooms.map_y IS 'Y coordinate for room position on the interactive map (admin layout). NULL if not set.';


--
-- Name: COLUMN rooms.map_origin_zone; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.rooms.map_origin_zone IS 'Marks this room as the origin for coordinate generation in its zone/subzone. Only one room per zone/subzone should be marked.';


--
-- Name: COLUMN rooms.map_symbol; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.rooms.map_symbol IS 'Admin-configurable ASCII symbol for this room on the map. If NULL, symbol is auto-assigned based on environment/type.';


--
-- Name: COLUMN rooms.map_style; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.rooms.map_style IS 'Style override for map rendering (e.g., "world", "city", "interior"). If NULL, style is determined from environment.';


--
-- Name: spells; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.spells (
    spell_id character varying(255) NOT NULL,
    name character varying(100) NOT NULL,
    description text NOT NULL,
    school character varying(50) NOT NULL,
    mp_cost integer NOT NULL,
    lucidity_cost integer DEFAULT 0 NOT NULL,
    corruption_on_learn integer DEFAULT 0 NOT NULL,
    corruption_on_cast integer DEFAULT 0 NOT NULL,
    casting_time_seconds integer DEFAULT 0 NOT NULL,
    target_type character varying(50) NOT NULL,
    range_type character varying(50) NOT NULL,
    effect_type character varying(50) NOT NULL,
    effect_data jsonb DEFAULT '{}'::jsonb NOT NULL,
    materials jsonb DEFAULT '[]'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT spells_casting_time_seconds_check CHECK ((casting_time_seconds >= 0)),
    CONSTRAINT spells_corruption_on_cast_check CHECK ((corruption_on_cast >= 0)),
    CONSTRAINT spells_corruption_on_learn_check CHECK ((corruption_on_learn >= 0)),
    CONSTRAINT spells_lucidity_cost_check CHECK ((lucidity_cost >= 0)),
    CONSTRAINT spells_mp_cost_check CHECK ((mp_cost >= 0)),
    CONSTRAINT spells_range_type_check CHECK (((range_type)::text = ANY ((ARRAY['touch'::character varying, 'same_room'::character varying, 'adjacent_room'::character varying, 'unlimited'::character varying])::text[]))),
    CONSTRAINT spells_school_check CHECK (((school)::text = ANY ((ARRAY['mythos'::character varying, 'clerical'::character varying, 'elemental'::character varying, 'other'::character varying])::text[]))),
    CONSTRAINT spells_target_type_check CHECK (((target_type)::text = ANY ((ARRAY['self'::character varying, 'entity'::character varying, 'location'::character varying, 'area'::character varying, 'all'::character varying])::text[])))
);


--
-- Name: TABLE spells; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.spells IS 'Global spell registry with spell definitions and properties.';


--
-- Name: subzones; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subzones (
    id uuid NOT NULL,
    zone_id uuid NOT NULL,
    stable_id text NOT NULL,
    name text NOT NULL,
    environment text,
    description text,
    special_rules jsonb DEFAULT '{}'::jsonb,
    CONSTRAINT chk_subzones_environment CHECK (((environment IS NULL) OR (environment = ANY (ARRAY['indoors'::text, 'outdoors'::text, 'underwater'::text, 'void'::text]))))
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id uuid NOT NULL,
    username text NOT NULL,
    display_name text NOT NULL,
    email text,
    password_hash text,
    is_admin boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    hashed_password character varying(255) DEFAULT ''::character varying NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    is_superuser boolean DEFAULT false NOT NULL,
    is_verified boolean DEFAULT false NOT NULL
);


--
-- Name: TABLE users; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.users IS 'Stores user account information for authentication and authorization.';


--
-- Name: COLUMN users.id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.users.id IS 'Primary key: UUID generated automatically.';


--
-- Name: COLUMN users.username; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.users.username IS 'User login name (must be unique).';


--
-- Name: COLUMN users.email; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.users.email IS 'User email address (must be unique).';


--
-- Name: zone_configurations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.zone_configurations (
    id uuid NOT NULL,
    zone_id uuid NOT NULL,
    subzone_id uuid NOT NULL
);


--
-- Name: zones; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.zones (
    id uuid NOT NULL,
    stable_id text NOT NULL,
    name text NOT NULL,
    zone_type text,
    environment text,
    description text,
    weather_patterns jsonb DEFAULT '[]'::jsonb,
    special_rules jsonb DEFAULT '{}'::jsonb,
    CONSTRAINT chk_zones_environment CHECK (((environment IS NULL) OR (environment = ANY (ARRAY['indoors'::text, 'outdoors'::text, 'underwater'::text, 'void'::text])))),
    CONSTRAINT chk_zones_zone_type CHECK (((zone_type IS NULL) OR (zone_type = ANY (ARRAY['city'::text, 'countryside'::text, 'mountains'::text, 'swamp'::text, 'tundra'::text, 'desert'::text, 'death'::text]))))
);


--
-- Name: aliases aliases_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.aliases
    ADD CONSTRAINT aliases_pkey PRIMARY KEY (id);


--
-- Name: aliases aliases_target_type_target_id_alias_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.aliases
    ADD CONSTRAINT aliases_target_type_target_id_alias_key UNIQUE (target_type, target_id, alias);


--
-- Name: calendar_holidays calendar_holidays_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.calendar_holidays
    ADD CONSTRAINT calendar_holidays_pkey PRIMARY KEY (id);


--
-- Name: calendar_holidays calendar_holidays_stable_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.calendar_holidays
    ADD CONSTRAINT calendar_holidays_stable_id_key UNIQUE (stable_id);


--
-- Name: calendar_npc_schedules calendar_npc_schedules_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.calendar_npc_schedules
    ADD CONSTRAINT calendar_npc_schedules_pkey PRIMARY KEY (id);


--
-- Name: calendar_npc_schedules calendar_npc_schedules_stable_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.calendar_npc_schedules
    ADD CONSTRAINT calendar_npc_schedules_stable_id_key UNIQUE (stable_id);


--
-- Name: container_contents container_contents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.container_contents
    ADD CONSTRAINT container_contents_pkey PRIMARY KEY (container_id, item_instance_id);


--
-- Name: containers containers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.containers
    ADD CONSTRAINT containers_pkey PRIMARY KEY (container_instance_id);


--
-- Name: emote_aliases emote_aliases_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.emote_aliases
    ADD CONSTRAINT emote_aliases_pkey PRIMARY KEY (emote_id, alias);


--
-- Name: emotes emotes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.emotes
    ADD CONSTRAINT emotes_pkey PRIMARY KEY (id);


--
-- Name: emotes emotes_stable_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.emotes
    ADD CONSTRAINT emotes_stable_id_key UNIQUE (stable_id);


--
-- Name: id_map_players id_map_players_new_uuid_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.id_map_players
    ADD CONSTRAINT id_map_players_new_uuid_key UNIQUE (new_uuid);


--
-- Name: id_map_players id_map_players_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.id_map_players
    ADD CONSTRAINT id_map_players_pkey PRIMARY KEY (old_sqlite_id);


--
-- Name: id_map_users id_map_users_new_uuid_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.id_map_users
    ADD CONSTRAINT id_map_users_new_uuid_key UNIQUE (new_uuid);


--
-- Name: id_map_users id_map_users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.id_map_users
    ADD CONSTRAINT id_map_users_pkey PRIMARY KEY (old_sqlite_id);


--
-- Name: invites invites_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invites
    ADD CONSTRAINT invites_code_key UNIQUE (invite_code);


--
-- Name: invites invites_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invites
    ADD CONSTRAINT invites_pkey PRIMARY KEY (id);


--
-- Name: invites invites_stable_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invites
    ADD CONSTRAINT invites_stable_id_key UNIQUE (stable_id);


--
-- Name: item_component_states item_component_states_item_instance_id_component_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_component_states
    ADD CONSTRAINT item_component_states_item_instance_id_component_id_key UNIQUE (item_instance_id, component_id);


--
-- Name: item_component_states item_component_states_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_component_states
    ADD CONSTRAINT item_component_states_pkey PRIMARY KEY (id);


--
-- Name: item_instances item_instances_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_instances
    ADD CONSTRAINT item_instances_pkey PRIMARY KEY (item_instance_id);


--
-- Name: item_prototypes item_prototypes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_prototypes
    ADD CONSTRAINT item_prototypes_pkey PRIMARY KEY (prototype_id);


--
-- Name: lucidity_adjustment_log lucidity_adjustment_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lucidity_adjustment_log
    ADD CONSTRAINT lucidity_adjustment_log_pkey PRIMARY KEY (id);


--
-- Name: lucidity_cooldowns lucidity_cooldowns_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lucidity_cooldowns
    ADD CONSTRAINT lucidity_cooldowns_pkey PRIMARY KEY (id);


--
-- Name: lucidity_cooldowns lucidity_cooldowns_player_id_action_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lucidity_cooldowns
    ADD CONSTRAINT lucidity_cooldowns_player_id_action_code_key UNIQUE (player_id, action_code);


--
-- Name: lucidity_exposure_state lucidity_exposure_state_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lucidity_exposure_state
    ADD CONSTRAINT lucidity_exposure_state_pkey PRIMARY KEY (id);


--
-- Name: lucidity_exposure_state lucidity_exposure_state_player_id_entity_archetype_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lucidity_exposure_state
    ADD CONSTRAINT lucidity_exposure_state_player_id_entity_archetype_key UNIQUE (player_id, entity_archetype);


--
-- Name: muting_rules muting_rules_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.muting_rules
    ADD CONSTRAINT muting_rules_pkey PRIMARY KEY (id);


--
-- Name: npc_definitions npc_definitions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.npc_definitions
    ADD CONSTRAINT npc_definitions_pkey PRIMARY KEY (id);


--
-- Name: npc_relationships npc_relationships_npc_id_1_npc_id_2_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.npc_relationships
    ADD CONSTRAINT npc_relationships_npc_id_1_npc_id_2_key UNIQUE (npc_id_1, npc_id_2);


--
-- Name: npc_relationships npc_relationships_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.npc_relationships
    ADD CONSTRAINT npc_relationships_pkey PRIMARY KEY (id);


--
-- Name: npc_spawn_rules npc_spawn_rules_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.npc_spawn_rules
    ADD CONSTRAINT npc_spawn_rules_pkey PRIMARY KEY (id);


--
-- Name: player_channel_preferences player_channel_preferences_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.player_channel_preferences
    ADD CONSTRAINT player_channel_preferences_pkey PRIMARY KEY (player_id);


--
-- Name: player_exploration player_exploration_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.player_exploration
    ADD CONSTRAINT player_exploration_pkey PRIMARY KEY (id);


--
-- Name: player_exploration player_exploration_player_room_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.player_exploration
    ADD CONSTRAINT player_exploration_player_room_unique UNIQUE (player_id, room_id);


--
-- Name: player_inventories player_inventories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.player_inventories
    ADD CONSTRAINT player_inventories_pkey PRIMARY KEY (player_id);


--
-- Name: player_lucidity player_lucidity_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.player_lucidity
    ADD CONSTRAINT player_lucidity_pkey PRIMARY KEY (player_id);


--
-- Name: player_spells player_spells_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.player_spells
    ADD CONSTRAINT player_spells_pkey PRIMARY KEY (id);


--
-- Name: player_spells player_spells_player_id_spell_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.player_spells
    ADD CONSTRAINT player_spells_player_id_spell_id_key UNIQUE (player_id, spell_id);


--
-- Name: players players_new_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.players
    ADD CONSTRAINT players_new_pkey PRIMARY KEY (player_id);


--
-- Name: professions professions_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.professions
    ADD CONSTRAINT professions_name_key UNIQUE (name);


--
-- Name: professions professions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.professions
    ADD CONSTRAINT professions_pkey PRIMARY KEY (id);


--
-- Name: room_links room_links_from_room_id_direction_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room_links
    ADD CONSTRAINT room_links_from_room_id_direction_key UNIQUE (from_room_id, direction);


--
-- Name: room_links room_links_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room_links
    ADD CONSTRAINT room_links_pkey PRIMARY KEY (id);


--
-- Name: rooms rooms_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT rooms_pkey PRIMARY KEY (id);


--
-- Name: rooms rooms_subzone_id_stable_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT rooms_subzone_id_stable_id_key UNIQUE (subzone_id, stable_id);


--
-- Name: spells spells_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.spells
    ADD CONSTRAINT spells_name_key UNIQUE (name);


--
-- Name: spells spells_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.spells
    ADD CONSTRAINT spells_pkey PRIMARY KEY (spell_id);


--
-- Name: subzones subzones_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subzones
    ADD CONSTRAINT subzones_pkey PRIMARY KEY (id);


--
-- Name: subzones subzones_zone_id_stable_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subzones
    ADD CONSTRAINT subzones_zone_id_stable_id_key UNIQUE (zone_id, stable_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: zone_configurations zone_configurations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.zone_configurations
    ADD CONSTRAINT zone_configurations_pkey PRIMARY KEY (id);


--
-- Name: zone_configurations zone_configurations_zone_id_subzone_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.zone_configurations
    ADD CONSTRAINT zone_configurations_zone_id_subzone_id_key UNIQUE (zone_id, subzone_id);


--
-- Name: zones zones_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.zones
    ADD CONSTRAINT zones_pkey PRIMARY KEY (id);


--
-- Name: zones zones_stable_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.zones
    ADD CONSTRAINT zones_stable_id_key UNIQUE (stable_id);


--
-- Name: idx_aliases_type_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_aliases_type_id ON public.aliases USING btree (target_type, target_id);


--
-- Name: idx_calendar_holidays_month_day; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_calendar_holidays_month_day ON public.calendar_holidays USING btree (month, day);


--
-- Name: idx_calendar_holidays_tradition; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_calendar_holidays_tradition ON public.calendar_holidays USING btree (tradition);


--
-- Name: idx_calendar_npc_schedules_category; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_calendar_npc_schedules_category ON public.calendar_npc_schedules USING btree (category);


--
-- Name: idx_calendar_npc_schedules_hours; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_calendar_npc_schedules_hours ON public.calendar_npc_schedules USING btree (start_hour, end_hour);


--
-- Name: idx_containers_decay_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_containers_decay_at ON public.containers USING btree (decay_at) WHERE (decay_at IS NOT NULL);


--
-- Name: idx_containers_entity_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_containers_entity_id ON public.containers USING btree (entity_id) WHERE (entity_id IS NOT NULL);


--
-- Name: idx_containers_owner_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_containers_owner_id ON public.containers USING btree (owner_id) WHERE (owner_id IS NOT NULL);


--
-- Name: idx_containers_room_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_containers_room_id ON public.containers USING btree (room_id) WHERE (room_id IS NOT NULL);


--
-- Name: idx_containers_source_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_containers_source_type ON public.containers USING btree (source_type);


--
-- Name: idx_emote_alias_on_alias; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_emote_alias_on_alias ON public.emote_aliases USING btree (alias);


--
-- Name: idx_invites_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_invites_active ON public.invites USING btree (is_active);


--
-- Name: idx_invites_expires_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_invites_expires_at ON public.invites USING btree (expires_at);


--
-- Name: idx_invites_used_by_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_invites_used_by_user_id ON public.invites USING btree (used_by_user_id);


--
-- Name: idx_item_component_states_instance_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_item_component_states_instance_id ON public.item_component_states USING btree (item_instance_id);


--
-- Name: idx_item_instances_owner; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_item_instances_owner ON public.item_instances USING btree (owner_type, owner_id);


--
-- Name: idx_item_instances_prototype_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_item_instances_prototype_id ON public.item_instances USING btree (prototype_id);


--
-- Name: idx_lucidity_adjustment_player_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_lucidity_adjustment_player_created ON public.lucidity_adjustment_log USING btree (player_id, created_at);


--
-- Name: idx_lucidity_adjustment_player_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_lucidity_adjustment_player_id ON public.lucidity_adjustment_log USING btree (player_id);


--
-- Name: idx_lucidity_cooldowns_player_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_lucidity_cooldowns_player_id ON public.lucidity_cooldowns USING btree (player_id);


--
-- Name: idx_lucidity_exposure_player_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_lucidity_exposure_player_id ON public.lucidity_exposure_state USING btree (player_id);


--
-- Name: idx_muting_expires_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_muting_expires_at ON public.muting_rules USING btree (expires_at);


--
-- Name: idx_npc_definitions_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_npc_definitions_name ON public.npc_definitions USING btree (name);


--
-- Name: idx_npc_definitions_name_sub_zone; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_npc_definitions_name_sub_zone ON public.npc_definitions USING btree (name, sub_zone_id);


--
-- Name: idx_npc_definitions_required; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_npc_definitions_required ON public.npc_definitions USING btree (required_npc);


--
-- Name: idx_npc_definitions_sub_zone; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_npc_definitions_sub_zone ON public.npc_definitions USING btree (sub_zone_id);


--
-- Name: idx_npc_definitions_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_npc_definitions_type ON public.npc_definitions USING btree (npc_type);


--
-- Name: idx_npc_relationships_npc1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_npc_relationships_npc1 ON public.npc_relationships USING btree (npc_id_1);


--
-- Name: idx_npc_relationships_npc2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_npc_relationships_npc2 ON public.npc_relationships USING btree (npc_id_2);


--
-- Name: idx_npc_spawn_rules_npc_def; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_npc_spawn_rules_npc_def ON public.npc_spawn_rules USING btree (npc_definition_id);


--
-- Name: idx_npc_spawn_rules_sub_zone; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_npc_spawn_rules_sub_zone ON public.npc_spawn_rules USING btree (sub_zone_id);


--
-- Name: idx_player_exploration_explored_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_player_exploration_explored_at ON public.player_exploration USING btree (explored_at);


--
-- Name: INDEX idx_player_exploration_explored_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON INDEX public.idx_player_exploration_explored_at IS 'Index for queries filtering by exploration time';


--
-- Name: idx_player_exploration_player_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_player_exploration_player_id ON public.player_exploration USING btree (player_id);


--
-- Name: INDEX idx_player_exploration_player_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON INDEX public.idx_player_exploration_player_id IS 'Index for fast lookups of all explored rooms for a specific player';


--
-- Name: idx_player_exploration_room_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_player_exploration_room_id ON public.player_exploration USING btree (room_id);


--
-- Name: INDEX idx_player_exploration_room_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON INDEX public.idx_player_exploration_room_id IS 'Index for reverse lookups of all players who have explored a specific room';


--
-- Name: idx_player_inventories_player_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_player_inventories_player_id ON public.player_inventories USING btree (player_id);


--
-- Name: idx_player_lucidity_tier; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_player_lucidity_tier ON public.player_lucidity USING btree (current_tier);


--
-- Name: idx_player_spells_player_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_player_spells_player_id ON public.player_spells USING btree (player_id);


--
-- Name: idx_player_spells_spell_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_player_spells_spell_id ON public.player_spells USING btree (spell_id);


--
-- Name: idx_players_is_admin; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_players_is_admin ON public.players USING btree (is_admin);


--
-- Name: idx_players_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_players_name ON public.players USING btree (name);


--
-- Name: idx_players_name_lower_unique_active; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_players_name_lower_unique_active ON public.players USING btree (lower((name)::text)) WHERE (is_deleted = false);


--
-- Name: idx_players_profession_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_players_profession_id ON public.players USING btree (profession_id);


--
-- Name: idx_players_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_players_user_id ON public.players USING btree (user_id);


--
-- Name: idx_players_user_id_is_deleted; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_players_user_id_is_deleted ON public.players USING btree (user_id, is_deleted);


--
-- Name: idx_professions_available; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_professions_available ON public.professions USING btree (is_available);


--
-- Name: idx_room_links_from; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_room_links_from ON public.room_links USING btree (from_room_id);


--
-- Name: idx_room_links_to; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_room_links_to ON public.room_links USING btree (to_room_id);


--
-- Name: idx_rooms_map_coordinates; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_rooms_map_coordinates ON public.rooms USING btree (map_x, map_y) WHERE ((map_x IS NOT NULL) AND (map_y IS NOT NULL));


--
-- Name: INDEX idx_rooms_map_coordinates; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON INDEX public.idx_rooms_map_coordinates IS 'Index for efficient spatial queries on rooms with map coordinates';


--
-- Name: idx_rooms_map_origin_zone; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_rooms_map_origin_zone ON public.rooms USING btree (map_origin_zone) WHERE (map_origin_zone = true);


--
-- Name: idx_rooms_subzone; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_rooms_subzone ON public.rooms USING btree (subzone_id);


--
-- Name: idx_spells_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_spells_name ON public.spells USING btree (name);


--
-- Name: idx_spells_school; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_spells_school ON public.spells USING btree (school);


--
-- Name: idx_subzones_zone; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_subzones_zone ON public.subzones USING btree (zone_id);


--
-- Name: idx_users_email; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_email ON public.users USING btree (email);


--
-- Name: idx_users_is_admin; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_is_admin ON public.users USING btree (is_admin);


--
-- Name: idx_users_username; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_username ON public.users USING btree (username);


--
-- Name: idx_users_username_lower_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_users_username_lower_unique ON public.users USING btree (lower(username));


--
-- Name: idx_zone_configs_subzone; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_zone_configs_subzone ON public.zone_configurations USING btree (subzone_id);


--
-- Name: idx_zone_configs_zone; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_zone_configs_zone ON public.zone_configurations USING btree (zone_id);


--
-- Name: ix_container_contents_container_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_container_contents_container_id ON public.container_contents USING btree (container_id);


--
-- Name: ix_container_contents_item_instance_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_container_contents_item_instance_id ON public.container_contents USING btree (item_instance_id);


--
-- Name: ix_container_contents_position; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_container_contents_position ON public.container_contents USING btree (container_id, "position");


--
-- Name: ix_containers_container_item_instance_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_containers_container_item_instance_id ON public.containers USING btree (container_item_instance_id);


--
-- Name: uq_muting_active_per_target; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_muting_active_per_target ON public.muting_rules USING btree (target_type, target_id) WHERE is_active;


--
-- Name: container_contents container_contents_container_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.container_contents
    ADD CONSTRAINT container_contents_container_id_fkey FOREIGN KEY (container_id) REFERENCES public.containers(container_instance_id) ON DELETE CASCADE;


--
-- Name: container_contents container_contents_item_instance_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.container_contents
    ADD CONSTRAINT container_contents_item_instance_id_fkey FOREIGN KEY (item_instance_id) REFERENCES public.item_instances(item_instance_id) ON DELETE CASCADE;


--
-- Name: containers containers_entity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.containers
    ADD CONSTRAINT containers_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES public.players(player_id) ON DELETE CASCADE;


--
-- Name: containers containers_owner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.containers
    ADD CONSTRAINT containers_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.players(player_id) ON DELETE SET NULL;


--
-- Name: emote_aliases emote_aliases_emote_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.emote_aliases
    ADD CONSTRAINT emote_aliases_emote_id_fkey FOREIGN KEY (emote_id) REFERENCES public.emotes(id) ON DELETE CASCADE;


--
-- Name: containers fk_containers_container_item_instance; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.containers
    ADD CONSTRAINT fk_containers_container_item_instance FOREIGN KEY (container_item_instance_id) REFERENCES public.item_instances(item_instance_id) ON DELETE SET NULL;


--
-- Name: id_map_players id_map_players_user_uuid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.id_map_players
    ADD CONSTRAINT id_map_players_user_uuid_fkey FOREIGN KEY (user_uuid) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: invites invites_created_by_user_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invites
    ADD CONSTRAINT invites_created_by_user_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: invites invites_used_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invites
    ADD CONSTRAINT invites_used_by_user_id_fkey FOREIGN KEY (used_by_user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: item_component_states item_component_states_item_instance_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_component_states
    ADD CONSTRAINT item_component_states_item_instance_id_fkey FOREIGN KEY (item_instance_id) REFERENCES public.item_instances(item_instance_id) ON DELETE CASCADE;


--
-- Name: item_instances item_instances_prototype_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_instances
    ADD CONSTRAINT item_instances_prototype_id_fkey FOREIGN KEY (prototype_id) REFERENCES public.item_prototypes(prototype_id) ON DELETE CASCADE;


--
-- Name: lucidity_adjustment_log lucidity_adjustment_log_player_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lucidity_adjustment_log
    ADD CONSTRAINT lucidity_adjustment_log_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(player_id) ON DELETE CASCADE;


--
-- Name: lucidity_cooldowns lucidity_cooldowns_player_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lucidity_cooldowns
    ADD CONSTRAINT lucidity_cooldowns_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(player_id) ON DELETE CASCADE;


--
-- Name: lucidity_exposure_state lucidity_exposure_state_player_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lucidity_exposure_state
    ADD CONSTRAINT lucidity_exposure_state_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(player_id) ON DELETE CASCADE;


--
-- Name: muting_rules muting_rules_created_by_user_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.muting_rules
    ADD CONSTRAINT muting_rules_created_by_user_fkey FOREIGN KEY (created_by_user) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: npc_relationships npc_relationships_npc_id_1_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.npc_relationships
    ADD CONSTRAINT npc_relationships_npc_id_1_fkey FOREIGN KEY (npc_id_1) REFERENCES public.npc_definitions(id) ON DELETE CASCADE;


--
-- Name: npc_relationships npc_relationships_npc_id_2_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.npc_relationships
    ADD CONSTRAINT npc_relationships_npc_id_2_fkey FOREIGN KEY (npc_id_2) REFERENCES public.npc_definitions(id) ON DELETE CASCADE;


--
-- Name: npc_spawn_rules npc_spawn_rules_npc_definition_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.npc_spawn_rules
    ADD CONSTRAINT npc_spawn_rules_npc_definition_id_fkey FOREIGN KEY (npc_definition_id) REFERENCES public.npc_definitions(id) ON DELETE CASCADE;


--
-- Name: player_channel_preferences player_channel_preferences_player_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.player_channel_preferences
    ADD CONSTRAINT player_channel_preferences_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(player_id) ON DELETE CASCADE;


--
-- Name: player_exploration player_exploration_player_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.player_exploration
    ADD CONSTRAINT player_exploration_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(player_id) ON DELETE CASCADE;


--
-- Name: player_exploration player_exploration_room_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.player_exploration
    ADD CONSTRAINT player_exploration_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.rooms(id) ON DELETE CASCADE;


--
-- Name: player_inventories player_inventories_player_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.player_inventories
    ADD CONSTRAINT player_inventories_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(player_id) ON DELETE CASCADE;


--
-- Name: player_lucidity player_lucidity_player_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.player_lucidity
    ADD CONSTRAINT player_lucidity_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(player_id) ON DELETE CASCADE;


--
-- Name: player_spells player_spells_player_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.player_spells
    ADD CONSTRAINT player_spells_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(player_id) ON DELETE CASCADE;


--
-- Name: player_spells player_spells_spell_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.player_spells
    ADD CONSTRAINT player_spells_spell_id_fkey FOREIGN KEY (spell_id) REFERENCES public.spells(spell_id) ON DELETE CASCADE;


--
-- Name: players players_new_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.players
    ADD CONSTRAINT players_new_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: room_links room_links_from_room_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room_links
    ADD CONSTRAINT room_links_from_room_id_fkey FOREIGN KEY (from_room_id) REFERENCES public.rooms(id) ON DELETE CASCADE;


--
-- Name: room_links room_links_to_room_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room_links
    ADD CONSTRAINT room_links_to_room_id_fkey FOREIGN KEY (to_room_id) REFERENCES public.rooms(id) ON DELETE RESTRICT;


--
-- Name: rooms rooms_subzone_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT rooms_subzone_id_fkey FOREIGN KEY (subzone_id) REFERENCES public.subzones(id) ON DELETE CASCADE;


--
-- Name: subzones subzones_zone_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subzones
    ADD CONSTRAINT subzones_zone_id_fkey FOREIGN KEY (zone_id) REFERENCES public.zones(id) ON DELETE CASCADE;


--
-- Name: zone_configurations zone_configurations_subzone_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.zone_configurations
    ADD CONSTRAINT zone_configurations_subzone_id_fkey FOREIGN KEY (subzone_id) REFERENCES public.subzones(id) ON DELETE CASCADE;


--
-- Name: zone_configurations zone_configurations_zone_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.zone_configurations
    ADD CONSTRAINT zone_configurations_zone_id_fkey FOREIGN KEY (zone_id) REFERENCES public.zones(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict rW9Vr6fObqp4Mf84U62beFOvje4PFw1XOwgcF0EcaHsiLVaZX9K7vpXjBOkp8AB
