-- Authoritative Database Schema
-- Generated from: mythos_dev database
-- Generated on: 2025-11-19 14:54:23 UTC
-- Generated by: scripts/generate_schema_from_dev.ps1
--
-- This file is the authoritative source of truth for the database schema.
-- It is generated directly from the mythos_dev database using pg_dump.
--
-- To regenerate this file:
--   1. Make schema changes in the mythos_dev database
--   2. Run: .\scripts\generate_schema_from_dev.ps1
--   3. Review the changes
--   4. Commit the updated file to git
--
-- SET statements for clean execution
SET client_min_messages = WARNING;
SET search_path = public;
--
-- PostgreSQL database dump
--

\restrict 9wgDAUNpT1eOAIH0i0DMbSjMLNdwKmkdYM53riAlkOJhGZGapfJkElb4oTIl4Ef

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.zone_configurations DROP CONSTRAINT IF EXISTS zone_configurations_zone_id_fkey;
ALTER TABLE IF EXISTS ONLY public.zone_configurations DROP CONSTRAINT IF EXISTS zone_configurations_subzone_id_fkey;
ALTER TABLE IF EXISTS ONLY public.subzones DROP CONSTRAINT IF EXISTS subzones_zone_id_fkey;
ALTER TABLE IF EXISTS ONLY public.sanity_exposure_state DROP CONSTRAINT IF EXISTS sanity_exposure_state_player_id_fkey;
ALTER TABLE IF EXISTS ONLY public.sanity_cooldowns DROP CONSTRAINT IF EXISTS sanity_cooldowns_player_id_fkey;
ALTER TABLE IF EXISTS ONLY public.sanity_adjustment_log DROP CONSTRAINT IF EXISTS sanity_adjustment_log_player_id_fkey;
ALTER TABLE IF EXISTS ONLY public.rooms DROP CONSTRAINT IF EXISTS rooms_subzone_id_fkey;
ALTER TABLE IF EXISTS ONLY public.room_links DROP CONSTRAINT IF EXISTS room_links_to_room_id_fkey;
ALTER TABLE IF EXISTS ONLY public.room_links DROP CONSTRAINT IF EXISTS room_links_from_room_id_fkey;
ALTER TABLE IF EXISTS ONLY public.players DROP CONSTRAINT IF EXISTS players_new_user_id_fkey;
ALTER TABLE IF EXISTS ONLY public.player_sanity DROP CONSTRAINT IF EXISTS player_sanity_player_id_fkey;
ALTER TABLE IF EXISTS ONLY public.player_inventories DROP CONSTRAINT IF EXISTS player_inventories_player_id_fkey;
ALTER TABLE IF EXISTS ONLY public.npc_spawn_rules DROP CONSTRAINT IF EXISTS npc_spawn_rules_npc_definition_id_fkey;
ALTER TABLE IF EXISTS ONLY public.npc_relationships DROP CONSTRAINT IF EXISTS npc_relationships_npc_id_2_fkey;
ALTER TABLE IF EXISTS ONLY public.npc_relationships DROP CONSTRAINT IF EXISTS npc_relationships_npc_id_1_fkey;
ALTER TABLE IF EXISTS ONLY public.muting_rules DROP CONSTRAINT IF EXISTS muting_rules_created_by_user_fkey;
ALTER TABLE IF EXISTS ONLY public.item_instances DROP CONSTRAINT IF EXISTS item_instances_prototype_id_fkey;
ALTER TABLE IF EXISTS ONLY public.item_component_states DROP CONSTRAINT IF EXISTS item_component_states_item_instance_id_fkey;
ALTER TABLE IF EXISTS ONLY public.invites DROP CONSTRAINT IF EXISTS invites_used_by_user_id_fkey;
ALTER TABLE IF EXISTS ONLY public.invites DROP CONSTRAINT IF EXISTS invites_created_by_user_fkey;
ALTER TABLE IF EXISTS ONLY public.id_map_players DROP CONSTRAINT IF EXISTS id_map_players_user_uuid_fkey;
ALTER TABLE IF EXISTS ONLY public.emote_aliases DROP CONSTRAINT IF EXISTS emote_aliases_emote_id_fkey;
DROP INDEX IF EXISTS public.uq_muting_active_per_target;
DROP INDEX IF EXISTS public.idx_zone_configs_zone;
DROP INDEX IF EXISTS public.idx_zone_configs_subzone;
DROP INDEX IF EXISTS public.idx_users_username;
DROP INDEX IF EXISTS public.idx_users_is_admin;
DROP INDEX IF EXISTS public.idx_users_email;
DROP INDEX IF EXISTS public.idx_subzones_zone;
DROP INDEX IF EXISTS public.idx_sanity_exposure_player_id;
DROP INDEX IF EXISTS public.idx_sanity_cooldowns_player_id;
DROP INDEX IF EXISTS public.idx_sanity_adjustment_player_id;
DROP INDEX IF EXISTS public.idx_sanity_adjustment_player_created;
DROP INDEX IF EXISTS public.idx_rooms_subzone;
DROP INDEX IF EXISTS public.idx_room_links_to;
DROP INDEX IF EXISTS public.idx_room_links_from;
DROP INDEX IF EXISTS public.idx_professions_available;
DROP INDEX IF EXISTS public.idx_players_user_id;
DROP INDEX IF EXISTS public.idx_players_profession_id;
DROP INDEX IF EXISTS public.idx_players_name;
DROP INDEX IF EXISTS public.idx_players_is_admin;
DROP INDEX IF EXISTS public.idx_player_sanity_tier;
DROP INDEX IF EXISTS public.idx_player_inventories_player_id;
DROP INDEX IF EXISTS public.idx_npc_spawn_rules_sub_zone;
DROP INDEX IF EXISTS public.idx_npc_spawn_rules_npc_def;
DROP INDEX IF EXISTS public.idx_npc_relationships_npc2;
DROP INDEX IF EXISTS public.idx_npc_relationships_npc1;
DROP INDEX IF EXISTS public.idx_npc_definitions_type;
DROP INDEX IF EXISTS public.idx_npc_definitions_sub_zone;
DROP INDEX IF EXISTS public.idx_npc_definitions_required;
DROP INDEX IF EXISTS public.idx_npc_definitions_name_sub_zone;
DROP INDEX IF EXISTS public.idx_npc_definitions_name;
DROP INDEX IF EXISTS public.idx_muting_expires_at;
DROP INDEX IF EXISTS public.idx_item_instances_prototype_id;
DROP INDEX IF EXISTS public.idx_item_instances_owner;
DROP INDEX IF EXISTS public.idx_item_component_states_instance_id;
DROP INDEX IF EXISTS public.idx_invites_used_by_user_id;
DROP INDEX IF EXISTS public.idx_invites_expires_at;
DROP INDEX IF EXISTS public.idx_invites_active;
DROP INDEX IF EXISTS public.idx_emote_alias_on_alias;
DROP INDEX IF EXISTS public.idx_calendar_npc_schedules_hours;
DROP INDEX IF EXISTS public.idx_calendar_npc_schedules_category;
DROP INDEX IF EXISTS public.idx_calendar_holidays_tradition;
DROP INDEX IF EXISTS public.idx_calendar_holidays_month_day;
DROP INDEX IF EXISTS public.idx_aliases_type_id;
ALTER TABLE IF EXISTS ONLY public.zones DROP CONSTRAINT IF EXISTS zones_stable_id_key;
ALTER TABLE IF EXISTS ONLY public.zones DROP CONSTRAINT IF EXISTS zones_pkey;
ALTER TABLE IF EXISTS ONLY public.zone_configurations DROP CONSTRAINT IF EXISTS zone_configurations_zone_id_subzone_id_key;
ALTER TABLE IF EXISTS ONLY public.zone_configurations DROP CONSTRAINT IF EXISTS zone_configurations_pkey;
ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT IF EXISTS users_username_key;
ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT IF EXISTS users_pkey;
ALTER TABLE IF EXISTS ONLY public.subzones DROP CONSTRAINT IF EXISTS subzones_zone_id_stable_id_key;
ALTER TABLE IF EXISTS ONLY public.subzones DROP CONSTRAINT IF EXISTS subzones_pkey;
ALTER TABLE IF EXISTS ONLY public.staging_users DROP CONSTRAINT IF EXISTS staging_users_pkey;
ALTER TABLE IF EXISTS ONLY public.staging_players DROP CONSTRAINT IF EXISTS staging_players_pkey;
ALTER TABLE IF EXISTS ONLY public.sanity_exposure_state DROP CONSTRAINT IF EXISTS sanity_exposure_state_player_id_entity_archetype_key;
ALTER TABLE IF EXISTS ONLY public.sanity_exposure_state DROP CONSTRAINT IF EXISTS sanity_exposure_state_pkey;
ALTER TABLE IF EXISTS ONLY public.sanity_cooldowns DROP CONSTRAINT IF EXISTS sanity_cooldowns_player_id_action_code_key;
ALTER TABLE IF EXISTS ONLY public.sanity_cooldowns DROP CONSTRAINT IF EXISTS sanity_cooldowns_pkey;
ALTER TABLE IF EXISTS ONLY public.sanity_adjustment_log DROP CONSTRAINT IF EXISTS sanity_adjustment_log_pkey;
ALTER TABLE IF EXISTS ONLY public.rooms DROP CONSTRAINT IF EXISTS rooms_subzone_id_stable_id_key;
ALTER TABLE IF EXISTS ONLY public.rooms DROP CONSTRAINT IF EXISTS rooms_pkey;
ALTER TABLE IF EXISTS ONLY public.room_links DROP CONSTRAINT IF EXISTS room_links_pkey;
ALTER TABLE IF EXISTS ONLY public.room_links DROP CONSTRAINT IF EXISTS room_links_from_room_id_direction_key;
ALTER TABLE IF EXISTS ONLY public.professions DROP CONSTRAINT IF EXISTS professions_pkey;
ALTER TABLE IF EXISTS ONLY public.professions DROP CONSTRAINT IF EXISTS professions_name_key;
ALTER TABLE IF EXISTS ONLY public.players DROP CONSTRAINT IF EXISTS players_new_user_id_key;
ALTER TABLE IF EXISTS ONLY public.players DROP CONSTRAINT IF EXISTS players_new_pkey;
ALTER TABLE IF EXISTS ONLY public.players DROP CONSTRAINT IF EXISTS players_new_name_key;
ALTER TABLE IF EXISTS ONLY public.player_sanity DROP CONSTRAINT IF EXISTS player_sanity_pkey;
ALTER TABLE IF EXISTS ONLY public.player_inventories DROP CONSTRAINT IF EXISTS player_inventories_pkey;
ALTER TABLE IF EXISTS ONLY public.npc_spawn_rules DROP CONSTRAINT IF EXISTS npc_spawn_rules_pkey;
ALTER TABLE IF EXISTS ONLY public.npc_relationships DROP CONSTRAINT IF EXISTS npc_relationships_pkey;
ALTER TABLE IF EXISTS ONLY public.npc_relationships DROP CONSTRAINT IF EXISTS npc_relationships_npc_id_1_npc_id_2_key;
ALTER TABLE IF EXISTS ONLY public.npc_definitions DROP CONSTRAINT IF EXISTS npc_definitions_pkey;
ALTER TABLE IF EXISTS ONLY public.muting_rules DROP CONSTRAINT IF EXISTS muting_rules_pkey;
ALTER TABLE IF EXISTS ONLY public.item_prototypes DROP CONSTRAINT IF EXISTS item_prototypes_pkey;
ALTER TABLE IF EXISTS ONLY public.item_instances DROP CONSTRAINT IF EXISTS item_instances_pkey;
ALTER TABLE IF EXISTS ONLY public.item_component_states DROP CONSTRAINT IF EXISTS item_component_states_pkey;
ALTER TABLE IF EXISTS ONLY public.item_component_states DROP CONSTRAINT IF EXISTS item_component_states_item_instance_id_component_id_key;
ALTER TABLE IF EXISTS ONLY public.invites DROP CONSTRAINT IF EXISTS invites_stable_id_key;
ALTER TABLE IF EXISTS ONLY public.invites DROP CONSTRAINT IF EXISTS invites_pkey;
ALTER TABLE IF EXISTS ONLY public.invites DROP CONSTRAINT IF EXISTS invites_code_key;
ALTER TABLE IF EXISTS ONLY public.id_map_users DROP CONSTRAINT IF EXISTS id_map_users_pkey;
ALTER TABLE IF EXISTS ONLY public.id_map_users DROP CONSTRAINT IF EXISTS id_map_users_new_uuid_key;
ALTER TABLE IF EXISTS ONLY public.id_map_players DROP CONSTRAINT IF EXISTS id_map_players_pkey;
ALTER TABLE IF EXISTS ONLY public.id_map_players DROP CONSTRAINT IF EXISTS id_map_players_new_uuid_key;
ALTER TABLE IF EXISTS ONLY public.emotes DROP CONSTRAINT IF EXISTS emotes_stable_id_key;
ALTER TABLE IF EXISTS ONLY public.emotes DROP CONSTRAINT IF EXISTS emotes_pkey;
ALTER TABLE IF EXISTS ONLY public.emote_aliases DROP CONSTRAINT IF EXISTS emote_aliases_pkey;
ALTER TABLE IF EXISTS ONLY public.calendar_npc_schedules DROP CONSTRAINT IF EXISTS calendar_npc_schedules_stable_id_key;
ALTER TABLE IF EXISTS ONLY public.calendar_npc_schedules DROP CONSTRAINT IF EXISTS calendar_npc_schedules_pkey;
ALTER TABLE IF EXISTS ONLY public.calendar_holidays DROP CONSTRAINT IF EXISTS calendar_holidays_stable_id_key;
ALTER TABLE IF EXISTS ONLY public.calendar_holidays DROP CONSTRAINT IF EXISTS calendar_holidays_pkey;
ALTER TABLE IF EXISTS ONLY public.aliases DROP CONSTRAINT IF EXISTS aliases_target_type_target_id_alias_key;
ALTER TABLE IF EXISTS ONLY public.aliases DROP CONSTRAINT IF EXISTS aliases_pkey;
ALTER TABLE IF EXISTS public.sanity_exposure_state ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.sanity_cooldowns ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.sanity_adjustment_log ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.professions ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.npc_spawn_rules ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.npc_relationships ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.npc_definitions ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.item_component_states ALTER COLUMN id DROP DEFAULT;
DROP TABLE IF EXISTS public.zones;
DROP TABLE IF EXISTS public.zone_configurations;
DROP TABLE IF EXISTS public.users;
DROP TABLE IF EXISTS public.subzones;
DROP TABLE IF EXISTS public.staging_users;
DROP TABLE IF EXISTS public.staging_players;
DROP SEQUENCE IF EXISTS public.sanity_exposure_state_id_seq;
DROP TABLE IF EXISTS public.sanity_exposure_state;
DROP SEQUENCE IF EXISTS public.sanity_cooldowns_id_seq;
DROP TABLE IF EXISTS public.sanity_cooldowns;
DROP SEQUENCE IF EXISTS public.sanity_adjustment_log_id_seq;
DROP TABLE IF EXISTS public.sanity_adjustment_log;
DROP TABLE IF EXISTS public.rooms;
DROP TABLE IF EXISTS public.room_links;
DROP SEQUENCE IF EXISTS public.professions_id_seq;
DROP TABLE IF EXISTS public.professions;
DROP TABLE IF EXISTS public.players_backup_migration;
DROP TABLE IF EXISTS public.players;
DROP TABLE IF EXISTS public.player_sanity;
DROP TABLE IF EXISTS public.player_inventories;
DROP SEQUENCE IF EXISTS public.npc_spawn_rules_id_seq;
DROP TABLE IF EXISTS public.npc_spawn_rules;
DROP SEQUENCE IF EXISTS public.npc_relationships_id_seq;
DROP TABLE IF EXISTS public.npc_relationships;
DROP SEQUENCE IF EXISTS public.npc_definitions_id_seq;
DROP TABLE IF EXISTS public.npc_definitions;
DROP TABLE IF EXISTS public.muting_rules;
DROP TABLE IF EXISTS public.item_prototypes;
DROP TABLE IF EXISTS public.item_instances;
DROP SEQUENCE IF EXISTS public.item_component_states_id_seq;
DROP TABLE IF EXISTS public.item_component_states;
DROP TABLE IF EXISTS public.invites;
DROP TABLE IF EXISTS public.id_map_users;
DROP TABLE IF EXISTS public.id_map_players;
DROP TABLE IF EXISTS public.emotes;
DROP TABLE IF EXISTS public.emote_aliases;
DROP TABLE IF EXISTS public.calendar_npc_schedules;
DROP TABLE IF EXISTS public.calendar_holidays;
DROP TABLE IF EXISTS public.aliases;
DROP TYPE IF EXISTS public.season_enum;
DROP EXTENSION IF EXISTS pgcrypto;
--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


--
-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';


--
-- Name: season_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.season_enum AS ENUM (
    'winter',
    'spring',
    'summer',
    'autumn'
);


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: aliases; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.aliases (
    id uuid NOT NULL,
    target_type text NOT NULL,
    target_id uuid NOT NULL,
    alias text NOT NULL
);


--
-- Name: calendar_holidays; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.calendar_holidays (
    id uuid NOT NULL,
    stable_id text NOT NULL,
    name text NOT NULL,
    tradition text NOT NULL,
    month smallint NOT NULL,
    day smallint NOT NULL,
    duration_hours smallint NOT NULL,
    season public.season_enum NOT NULL,
    bonus_tags text[] DEFAULT '{}'::text[] NOT NULL,
    CONSTRAINT calendar_holidays_day_check CHECK (((day >= 1) AND (day <= 31))),
    CONSTRAINT calendar_holidays_duration_hours_check CHECK (((duration_hours >= 1) AND (duration_hours <= 168))),
    CONSTRAINT calendar_holidays_month_check CHECK (((month >= 1) AND (month <= 12)))
);


--
-- Name: calendar_npc_schedules; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.calendar_npc_schedules (
    id uuid NOT NULL,
    stable_id text NOT NULL,
    name text NOT NULL,
    category text NOT NULL,
    start_hour smallint NOT NULL,
    end_hour smallint NOT NULL,
    days text[] NOT NULL,
    applies_to text[] NOT NULL,
    effects text[] NOT NULL,
    notes text,
    CONSTRAINT calendar_npc_schedules_end_hour_check CHECK (((end_hour >= 0) AND (end_hour <= 24))),
    CONSTRAINT calendar_npc_schedules_start_hour_check CHECK (((start_hour >= 0) AND (start_hour <= 24)))
);


--
-- Name: emote_aliases; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.emote_aliases (
    emote_id uuid NOT NULL,
    alias text NOT NULL
);


--
-- Name: emotes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.emotes (
    id uuid NOT NULL,
    stable_id text NOT NULL,
    self_message text NOT NULL,
    other_message text NOT NULL
);


--
-- Name: id_map_players; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.id_map_players (
    old_sqlite_id text NOT NULL,
    new_uuid uuid NOT NULL,
    user_uuid uuid NOT NULL,
    name text
);


--
-- Name: id_map_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.id_map_users (
    old_sqlite_id text NOT NULL,
    new_uuid uuid NOT NULL,
    username text
);


--
-- Name: invites; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.invites (
    id uuid NOT NULL,
    stable_id text,
    invite_code text CONSTRAINT invites_code_not_null NOT NULL,
    description text,
    created_by_user_id uuid,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone,
    used_by_user_id uuid
);


--
-- Name: item_component_states; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.item_component_states (
    id integer NOT NULL,
    item_instance_id character varying(64) NOT NULL,
    component_id character varying(120) NOT NULL,
    state_payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: item_component_states_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.item_component_states_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: item_component_states_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.item_component_states_id_seq OWNED BY public.item_component_states.id;


--
-- Name: item_instances; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.item_instances (
    item_instance_id character varying(64) NOT NULL,
    prototype_id character varying(120) NOT NULL,
    owner_type character varying(32) DEFAULT 'room'::character varying NOT NULL,
    owner_id character varying(255),
    location_context character varying(255),
    quantity integer DEFAULT 1 NOT NULL,
    condition integer,
    flags_override jsonb DEFAULT '[]'::jsonb NOT NULL,
    binding_state character varying(32),
    attunement_state jsonb DEFAULT '{}'::jsonb NOT NULL,
    custom_name character varying(255),
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    origin_source character varying(64),
    origin_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: item_prototypes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.item_prototypes (
    prototype_id character varying(120) NOT NULL,
    name character varying(120) NOT NULL,
    short_description character varying(255) NOT NULL,
    long_description text NOT NULL,
    item_type character varying(32) NOT NULL,
    weight double precision DEFAULT 0.0 NOT NULL,
    base_value integer DEFAULT 0 NOT NULL,
    durability integer,
    flags jsonb DEFAULT '[]'::jsonb NOT NULL,
    wear_slots jsonb DEFAULT '[]'::jsonb NOT NULL,
    stacking_rules jsonb DEFAULT '{}'::jsonb NOT NULL,
    usage_restrictions jsonb DEFAULT '{}'::jsonb NOT NULL,
    effect_components jsonb DEFAULT '[]'::jsonb NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    tags jsonb DEFAULT '[]'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: muting_rules; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.muting_rules (
    id uuid NOT NULL,
    target_type text NOT NULL,
    target_id uuid NOT NULL,
    reason text,
    created_by_user uuid,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone
);


--
-- Name: npc_definitions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.npc_definitions (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    npc_type character varying(20) NOT NULL,
    sub_zone_id character varying(50) NOT NULL,
    room_id character varying(50),
    required_npc boolean DEFAULT false NOT NULL,
    max_population integer DEFAULT 1 NOT NULL,
    spawn_probability real DEFAULT 1.0 NOT NULL,
    base_stats text DEFAULT '{}'::text NOT NULL,
    behavior_config text DEFAULT '{}'::text NOT NULL,
    ai_integration_stub text DEFAULT '{}'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT npc_definitions_npc_type_check CHECK (((npc_type)::text = ANY ((ARRAY['shopkeeper'::character varying, 'quest_giver'::character varying, 'passive_mob'::character varying, 'aggressive_mob'::character varying])::text[])))
);


--
-- Name: npc_definitions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.npc_definitions_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: npc_definitions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.npc_definitions_id_seq OWNED BY public.npc_definitions.id;


--
-- Name: npc_relationships; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.npc_relationships (
    id integer NOT NULL,
    npc_id_1 integer NOT NULL,
    npc_id_2 integer NOT NULL,
    relationship_type character varying(20) NOT NULL,
    relationship_strength real DEFAULT 0.5,
    CONSTRAINT npc_relationships_relationship_type_check CHECK (((relationship_type)::text = ANY ((ARRAY['ally'::character varying, 'enemy'::character varying, 'neutral'::character varying, 'follower'::character varying])::text[])))
);


--
-- Name: npc_relationships_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.npc_relationships_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: npc_relationships_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.npc_relationships_id_seq OWNED BY public.npc_relationships.id;


--
-- Name: npc_spawn_rules; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.npc_spawn_rules (
    id integer NOT NULL,
    npc_definition_id integer NOT NULL,
    sub_zone_id character varying(50) NOT NULL,
    min_population integer DEFAULT 0,
    max_population integer DEFAULT 999,
    spawn_conditions text DEFAULT '{}'::text NOT NULL
);


--
-- Name: npc_spawn_rules_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.npc_spawn_rules_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: npc_spawn_rules_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.npc_spawn_rules_id_seq OWNED BY public.npc_spawn_rules.id;


--
-- Name: player_inventories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.player_inventories (
    player_id character varying(255) NOT NULL,
    inventory_json text DEFAULT '[]'::text NOT NULL,
    equipped_json text DEFAULT '{}'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: player_sanity; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.player_sanity (
    player_id character varying(255) NOT NULL,
    current_san integer DEFAULT 100 NOT NULL,
    current_tier character varying(32) DEFAULT 'lucid'::character varying NOT NULL,
    liabilities text DEFAULT '[]'::text NOT NULL,
    last_updated_at timestamp with time zone DEFAULT now() NOT NULL,
    catatonia_entered_at timestamp with time zone,
    CONSTRAINT player_sanity_current_san_check CHECK (((current_san >= '-100'::integer) AND (current_san <= 100))),
    CONSTRAINT player_sanity_current_tier_check CHECK (((current_tier)::text = ANY ((ARRAY['lucid'::character varying, 'uneasy'::character varying, 'fractured'::character varying, 'deranged'::character varying, 'catatonic'::character varying])::text[])))
);


--
-- Name: players; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.players (
    player_id character varying(255) CONSTRAINT players_new_player_id_not_null NOT NULL,
    user_id uuid CONSTRAINT players_new_user_id_not_null NOT NULL,
    name character varying(50) CONSTRAINT players_new_name_not_null NOT NULL,
    inventory text DEFAULT '[]'::text CONSTRAINT players_new_inventory_not_null NOT NULL,
    status_effects text DEFAULT '[]'::text CONSTRAINT players_new_status_effects_not_null NOT NULL,
    current_room_id character varying(255) DEFAULT 'earth_arkhamcity_sanitarium_room_foyer_001'::character varying CONSTRAINT players_new_current_room_id_not_null NOT NULL,
    respawn_room_id character varying(100) DEFAULT 'earth_arkhamcity_sanitarium_room_foyer_001'::character varying,
    experience_points integer DEFAULT 0 CONSTRAINT players_new_experience_points_not_null NOT NULL,
    level integer DEFAULT 1 CONSTRAINT players_new_level_not_null NOT NULL,
    is_admin integer DEFAULT 0 CONSTRAINT players_new_is_admin_not_null NOT NULL,
    profession_id integer,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT players_new_created_at_not_null NOT NULL,
    last_active timestamp with time zone DEFAULT now() CONSTRAINT players_new_last_active_not_null NOT NULL,
    stats jsonb DEFAULT '{"fear": 0, "sanity": 100, "wisdom": 10, "charisma": 10, "position": "standing", "strength": 10, "dexterity": 10, "corruption": 0, "constitution": 10, "intelligence": 10, "current_health": 100, "cult_affiliation": 0, "occult_knowledge": 0}'::jsonb CONSTRAINT players_stats_jsonb_not_null NOT NULL
);


--
-- Name: players_backup_migration; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.players_backup_migration (
    id uuid,
    user_id uuid,
    name text,
    profession_id uuid,
    sanity_score integer,
    attributes jsonb,
    created_at timestamp with time zone,
    updated_at timestamp with time zone
);


--
-- Name: professions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.professions (
    id integer NOT NULL,
    name character varying(50) NOT NULL,
    description text NOT NULL,
    flavor_text text NOT NULL,
    stat_requirements text DEFAULT '{}'::text NOT NULL,
    mechanical_effects text DEFAULT '{}'::text NOT NULL,
    is_available boolean DEFAULT true NOT NULL
);


--
-- Name: professions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.professions_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: professions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.professions_id_seq OWNED BY public.professions.id;


--
-- Name: room_links; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.room_links (
    id uuid NOT NULL,
    from_room_id uuid NOT NULL,
    to_room_id uuid NOT NULL,
    direction text NOT NULL,
    attributes jsonb DEFAULT '{}'::jsonb NOT NULL
);


--
-- Name: rooms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rooms (
    id uuid NOT NULL,
    subzone_id uuid NOT NULL,
    stable_id text NOT NULL,
    name text NOT NULL,
    description text NOT NULL,
    attributes jsonb DEFAULT '{}'::jsonb NOT NULL
);


--
-- Name: sanity_adjustment_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sanity_adjustment_log (
    id integer NOT NULL,
    player_id character varying(255) NOT NULL,
    delta integer NOT NULL,
    reason_code character varying(64) NOT NULL,
    metadata text DEFAULT '{}'::text NOT NULL,
    location_id character varying(255),
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: sanity_adjustment_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.sanity_adjustment_log_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: sanity_adjustment_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.sanity_adjustment_log_id_seq OWNED BY public.sanity_adjustment_log.id;


--
-- Name: sanity_cooldowns; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sanity_cooldowns (
    id integer NOT NULL,
    player_id character varying(255) NOT NULL,
    action_code character varying(64) NOT NULL,
    cooldown_expires_at timestamp with time zone NOT NULL
);


--
-- Name: sanity_cooldowns_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.sanity_cooldowns_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: sanity_cooldowns_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.sanity_cooldowns_id_seq OWNED BY public.sanity_cooldowns.id;


--
-- Name: sanity_exposure_state; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sanity_exposure_state (
    id integer NOT NULL,
    player_id character varying(255) NOT NULL,
    entity_archetype character varying(128) NOT NULL,
    encounter_count integer DEFAULT 0 NOT NULL,
    last_encounter_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: sanity_exposure_state_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.sanity_exposure_state_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: sanity_exposure_state_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.sanity_exposure_state_id_seq OWNED BY public.sanity_exposure_state.id;


--
-- Name: staging_players; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.staging_players (
    old_sqlite_id text NOT NULL,
    user_id text,
    name text,
    is_admin boolean,
    profession_sqlite_id integer,
    stats_json text,
    inventory_json text,
    status_effects_json text,
    current_room_id text,
    respawn_room_id text,
    experience_points integer,
    level integer,
    created_at timestamp with time zone,
    last_active timestamp with time zone
);


--
-- Name: staging_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.staging_users (
    old_sqlite_id text NOT NULL,
    username text,
    email text,
    hashed_password text,
    is_active boolean,
    is_superuser boolean,
    is_verified boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone
);


--
-- Name: subzones; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subzones (
    id uuid NOT NULL,
    zone_id uuid NOT NULL,
    stable_id text NOT NULL,
    name text NOT NULL,
    environment text,
    description text,
    special_rules jsonb DEFAULT '{}'::jsonb,
    CONSTRAINT chk_subzones_environment CHECK (((environment IS NULL) OR (environment = ANY (ARRAY['indoors'::text, 'outdoors'::text, 'underwater'::text, 'void'::text]))))
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id uuid NOT NULL,
    username text NOT NULL,
    display_name text NOT NULL,
    email text,
    password_hash text,
    is_admin boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    hashed_password character varying(255) DEFAULT ''::character varying NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    is_superuser boolean DEFAULT false NOT NULL,
    is_verified boolean DEFAULT false NOT NULL
);


--
-- Name: zone_configurations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.zone_configurations (
    id uuid NOT NULL,
    zone_id uuid NOT NULL,
    subzone_id uuid NOT NULL
);


--
-- Name: zones; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.zones (
    id uuid NOT NULL,
    stable_id text NOT NULL,
    name text NOT NULL,
    zone_type text,
    environment text,
    description text,
    weather_patterns jsonb DEFAULT '[]'::jsonb,
    special_rules jsonb DEFAULT '{}'::jsonb,
    CONSTRAINT chk_zones_environment CHECK (((environment IS NULL) OR (environment = ANY (ARRAY['indoors'::text, 'outdoors'::text, 'underwater'::text, 'void'::text])))),
    CONSTRAINT chk_zones_zone_type CHECK (((zone_type IS NULL) OR (zone_type = ANY (ARRAY['city'::text, 'countryside'::text, 'mountains'::text, 'swamp'::text, 'tundra'::text, 'desert'::text, 'death'::text]))))
);


--
-- Name: item_component_states id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_component_states ALTER COLUMN id SET DEFAULT nextval('public.item_component_states_id_seq'::regclass);


--
-- Name: npc_definitions id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.npc_definitions ALTER COLUMN id SET DEFAULT nextval('public.npc_definitions_id_seq'::regclass);


--
-- Name: npc_relationships id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.npc_relationships ALTER COLUMN id SET DEFAULT nextval('public.npc_relationships_id_seq'::regclass);


--
-- Name: npc_spawn_rules id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.npc_spawn_rules ALTER COLUMN id SET DEFAULT nextval('public.npc_spawn_rules_id_seq'::regclass);


--
-- Name: professions id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.professions ALTER COLUMN id SET DEFAULT nextval('public.professions_id_seq'::regclass);


--
-- Name: sanity_adjustment_log id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sanity_adjustment_log ALTER COLUMN id SET DEFAULT nextval('public.sanity_adjustment_log_id_seq'::regclass);


--
-- Name: sanity_cooldowns id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sanity_cooldowns ALTER COLUMN id SET DEFAULT nextval('public.sanity_cooldowns_id_seq'::regclass);


--
-- Name: sanity_exposure_state id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sanity_exposure_state ALTER COLUMN id SET DEFAULT nextval('public.sanity_exposure_state_id_seq'::regclass);


--
-- Name: aliases aliases_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.aliases
    ADD CONSTRAINT aliases_pkey PRIMARY KEY (id);


--
-- Name: aliases aliases_target_type_target_id_alias_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.aliases
    ADD CONSTRAINT aliases_target_type_target_id_alias_key UNIQUE (target_type, target_id, alias);


--
-- Name: calendar_holidays calendar_holidays_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.calendar_holidays
    ADD CONSTRAINT calendar_holidays_pkey PRIMARY KEY (id);


--
-- Name: calendar_holidays calendar_holidays_stable_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.calendar_holidays
    ADD CONSTRAINT calendar_holidays_stable_id_key UNIQUE (stable_id);


--
-- Name: calendar_npc_schedules calendar_npc_schedules_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.calendar_npc_schedules
    ADD CONSTRAINT calendar_npc_schedules_pkey PRIMARY KEY (id);


--
-- Name: calendar_npc_schedules calendar_npc_schedules_stable_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.calendar_npc_schedules
    ADD CONSTRAINT calendar_npc_schedules_stable_id_key UNIQUE (stable_id);


--
-- Name: emote_aliases emote_aliases_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.emote_aliases
    ADD CONSTRAINT emote_aliases_pkey PRIMARY KEY (emote_id, alias);


--
-- Name: emotes emotes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.emotes
    ADD CONSTRAINT emotes_pkey PRIMARY KEY (id);


--
-- Name: emotes emotes_stable_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.emotes
    ADD CONSTRAINT emotes_stable_id_key UNIQUE (stable_id);


--
-- Name: id_map_players id_map_players_new_uuid_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.id_map_players
    ADD CONSTRAINT id_map_players_new_uuid_key UNIQUE (new_uuid);


--
-- Name: id_map_players id_map_players_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.id_map_players
    ADD CONSTRAINT id_map_players_pkey PRIMARY KEY (old_sqlite_id);


--
-- Name: id_map_users id_map_users_new_uuid_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.id_map_users
    ADD CONSTRAINT id_map_users_new_uuid_key UNIQUE (new_uuid);


--
-- Name: id_map_users id_map_users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.id_map_users
    ADD CONSTRAINT id_map_users_pkey PRIMARY KEY (old_sqlite_id);


--
-- Name: invites invites_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invites
    ADD CONSTRAINT invites_code_key UNIQUE (invite_code);


--
-- Name: invites invites_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invites
    ADD CONSTRAINT invites_pkey PRIMARY KEY (id);


--
-- Name: invites invites_stable_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invites
    ADD CONSTRAINT invites_stable_id_key UNIQUE (stable_id);


--
-- Name: item_component_states item_component_states_item_instance_id_component_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_component_states
    ADD CONSTRAINT item_component_states_item_instance_id_component_id_key UNIQUE (item_instance_id, component_id);


--
-- Name: item_component_states item_component_states_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_component_states
    ADD CONSTRAINT item_component_states_pkey PRIMARY KEY (id);


--
-- Name: item_instances item_instances_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_instances
    ADD CONSTRAINT item_instances_pkey PRIMARY KEY (item_instance_id);


--
-- Name: item_prototypes item_prototypes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_prototypes
    ADD CONSTRAINT item_prototypes_pkey PRIMARY KEY (prototype_id);


--
-- Name: muting_rules muting_rules_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.muting_rules
    ADD CONSTRAINT muting_rules_pkey PRIMARY KEY (id);


--
-- Name: npc_definitions npc_definitions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.npc_definitions
    ADD CONSTRAINT npc_definitions_pkey PRIMARY KEY (id);


--
-- Name: npc_relationships npc_relationships_npc_id_1_npc_id_2_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.npc_relationships
    ADD CONSTRAINT npc_relationships_npc_id_1_npc_id_2_key UNIQUE (npc_id_1, npc_id_2);


--
-- Name: npc_relationships npc_relationships_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.npc_relationships
    ADD CONSTRAINT npc_relationships_pkey PRIMARY KEY (id);


--
-- Name: npc_spawn_rules npc_spawn_rules_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.npc_spawn_rules
    ADD CONSTRAINT npc_spawn_rules_pkey PRIMARY KEY (id);


--
-- Name: player_inventories player_inventories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.player_inventories
    ADD CONSTRAINT player_inventories_pkey PRIMARY KEY (player_id);


--
-- Name: player_sanity player_sanity_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.player_sanity
    ADD CONSTRAINT player_sanity_pkey PRIMARY KEY (player_id);


--
-- Name: players players_new_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.players
    ADD CONSTRAINT players_new_name_key UNIQUE (name);


--
-- Name: players players_new_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.players
    ADD CONSTRAINT players_new_pkey PRIMARY KEY (player_id);


--
-- Name: players players_new_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.players
    ADD CONSTRAINT players_new_user_id_key UNIQUE (user_id);


--
-- Name: professions professions_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.professions
    ADD CONSTRAINT professions_name_key UNIQUE (name);


--
-- Name: professions professions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.professions
    ADD CONSTRAINT professions_pkey PRIMARY KEY (id);


--
-- Name: room_links room_links_from_room_id_direction_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room_links
    ADD CONSTRAINT room_links_from_room_id_direction_key UNIQUE (from_room_id, direction);


--
-- Name: room_links room_links_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room_links
    ADD CONSTRAINT room_links_pkey PRIMARY KEY (id);


--
-- Name: rooms rooms_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT rooms_pkey PRIMARY KEY (id);


--
-- Name: rooms rooms_subzone_id_stable_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT rooms_subzone_id_stable_id_key UNIQUE (subzone_id, stable_id);


--
-- Name: sanity_adjustment_log sanity_adjustment_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sanity_adjustment_log
    ADD CONSTRAINT sanity_adjustment_log_pkey PRIMARY KEY (id);


--
-- Name: sanity_cooldowns sanity_cooldowns_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sanity_cooldowns
    ADD CONSTRAINT sanity_cooldowns_pkey PRIMARY KEY (id);


--
-- Name: sanity_cooldowns sanity_cooldowns_player_id_action_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sanity_cooldowns
    ADD CONSTRAINT sanity_cooldowns_player_id_action_code_key UNIQUE (player_id, action_code);


--
-- Name: sanity_exposure_state sanity_exposure_state_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sanity_exposure_state
    ADD CONSTRAINT sanity_exposure_state_pkey PRIMARY KEY (id);


--
-- Name: sanity_exposure_state sanity_exposure_state_player_id_entity_archetype_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sanity_exposure_state
    ADD CONSTRAINT sanity_exposure_state_player_id_entity_archetype_key UNIQUE (player_id, entity_archetype);


--
-- Name: staging_players staging_players_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.staging_players
    ADD CONSTRAINT staging_players_pkey PRIMARY KEY (old_sqlite_id);


--
-- Name: staging_users staging_users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.staging_users
    ADD CONSTRAINT staging_users_pkey PRIMARY KEY (old_sqlite_id);


--
-- Name: subzones subzones_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subzones
    ADD CONSTRAINT subzones_pkey PRIMARY KEY (id);


--
-- Name: subzones subzones_zone_id_stable_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subzones
    ADD CONSTRAINT subzones_zone_id_stable_id_key UNIQUE (zone_id, stable_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: zone_configurations zone_configurations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.zone_configurations
    ADD CONSTRAINT zone_configurations_pkey PRIMARY KEY (id);


--
-- Name: zone_configurations zone_configurations_zone_id_subzone_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.zone_configurations
    ADD CONSTRAINT zone_configurations_zone_id_subzone_id_key UNIQUE (zone_id, subzone_id);


--
-- Name: zones zones_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.zones
    ADD CONSTRAINT zones_pkey PRIMARY KEY (id);


--
-- Name: zones zones_stable_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.zones
    ADD CONSTRAINT zones_stable_id_key UNIQUE (stable_id);


--
-- Name: idx_aliases_type_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_aliases_type_id ON public.aliases USING btree (target_type, target_id);


--
-- Name: idx_calendar_holidays_month_day; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_calendar_holidays_month_day ON public.calendar_holidays USING btree (month, day);


--
-- Name: idx_calendar_holidays_tradition; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_calendar_holidays_tradition ON public.calendar_holidays USING btree (tradition);


--
-- Name: idx_calendar_npc_schedules_category; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_calendar_npc_schedules_category ON public.calendar_npc_schedules USING btree (category);


--
-- Name: idx_calendar_npc_schedules_hours; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_calendar_npc_schedules_hours ON public.calendar_npc_schedules USING btree (start_hour, end_hour);


--
-- Name: idx_emote_alias_on_alias; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_emote_alias_on_alias ON public.emote_aliases USING btree (alias);


--
-- Name: idx_invites_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_invites_active ON public.invites USING btree (is_active);


--
-- Name: idx_invites_expires_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_invites_expires_at ON public.invites USING btree (expires_at);


--
-- Name: idx_invites_used_by_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_invites_used_by_user_id ON public.invites USING btree (used_by_user_id);


--
-- Name: idx_item_component_states_instance_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_item_component_states_instance_id ON public.item_component_states USING btree (item_instance_id);


--
-- Name: idx_item_instances_owner; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_item_instances_owner ON public.item_instances USING btree (owner_type, owner_id);


--
-- Name: idx_item_instances_prototype_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_item_instances_prototype_id ON public.item_instances USING btree (prototype_id);


--
-- Name: idx_muting_expires_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_muting_expires_at ON public.muting_rules USING btree (expires_at);


--
-- Name: idx_npc_definitions_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_npc_definitions_name ON public.npc_definitions USING btree (name);


--
-- Name: idx_npc_definitions_name_sub_zone; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_npc_definitions_name_sub_zone ON public.npc_definitions USING btree (name, sub_zone_id);


--
-- Name: idx_npc_definitions_required; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_npc_definitions_required ON public.npc_definitions USING btree (required_npc);


--
-- Name: idx_npc_definitions_sub_zone; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_npc_definitions_sub_zone ON public.npc_definitions USING btree (sub_zone_id);


--
-- Name: idx_npc_definitions_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_npc_definitions_type ON public.npc_definitions USING btree (npc_type);


--
-- Name: idx_npc_relationships_npc1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_npc_relationships_npc1 ON public.npc_relationships USING btree (npc_id_1);


--
-- Name: idx_npc_relationships_npc2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_npc_relationships_npc2 ON public.npc_relationships USING btree (npc_id_2);


--
-- Name: idx_npc_spawn_rules_npc_def; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_npc_spawn_rules_npc_def ON public.npc_spawn_rules USING btree (npc_definition_id);


--
-- Name: idx_npc_spawn_rules_sub_zone; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_npc_spawn_rules_sub_zone ON public.npc_spawn_rules USING btree (sub_zone_id);


--
-- Name: idx_player_inventories_player_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_player_inventories_player_id ON public.player_inventories USING btree (player_id);


--
-- Name: idx_player_sanity_tier; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_player_sanity_tier ON public.player_sanity USING btree (current_tier);


--
-- Name: idx_players_is_admin; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_players_is_admin ON public.players USING btree (is_admin);


--
-- Name: idx_players_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_players_name ON public.players USING btree (name);


--
-- Name: idx_players_profession_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_players_profession_id ON public.players USING btree (profession_id);


--
-- Name: idx_players_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_players_user_id ON public.players USING btree (user_id);


--
-- Name: idx_professions_available; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_professions_available ON public.professions USING btree (is_available);


--
-- Name: idx_room_links_from; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_room_links_from ON public.room_links USING btree (from_room_id);


--
-- Name: idx_room_links_to; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_room_links_to ON public.room_links USING btree (to_room_id);


--
-- Name: idx_rooms_subzone; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_rooms_subzone ON public.rooms USING btree (subzone_id);


--
-- Name: idx_sanity_adjustment_player_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sanity_adjustment_player_created ON public.sanity_adjustment_log USING btree (player_id, created_at);


--
-- Name: idx_sanity_adjustment_player_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sanity_adjustment_player_id ON public.sanity_adjustment_log USING btree (player_id);


--
-- Name: idx_sanity_cooldowns_player_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sanity_cooldowns_player_id ON public.sanity_cooldowns USING btree (player_id);


--
-- Name: idx_sanity_exposure_player_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sanity_exposure_player_id ON public.sanity_exposure_state USING btree (player_id);


--
-- Name: idx_subzones_zone; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_subzones_zone ON public.subzones USING btree (zone_id);


--
-- Name: idx_users_email; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_email ON public.users USING btree (email);


--
-- Name: idx_users_is_admin; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_is_admin ON public.users USING btree (is_admin);


--
-- Name: idx_users_username; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_username ON public.users USING btree (username);


--
-- Name: idx_zone_configs_subzone; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_zone_configs_subzone ON public.zone_configurations USING btree (subzone_id);


--
-- Name: idx_zone_configs_zone; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_zone_configs_zone ON public.zone_configurations USING btree (zone_id);


--
-- Name: uq_muting_active_per_target; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_muting_active_per_target ON public.muting_rules USING btree (target_type, target_id) WHERE is_active;


--
-- Name: emote_aliases emote_aliases_emote_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.emote_aliases
    ADD CONSTRAINT emote_aliases_emote_id_fkey FOREIGN KEY (emote_id) REFERENCES public.emotes(id) ON DELETE CASCADE;


--
-- Name: id_map_players id_map_players_user_uuid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.id_map_players
    ADD CONSTRAINT id_map_players_user_uuid_fkey FOREIGN KEY (user_uuid) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: invites invites_created_by_user_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invites
    ADD CONSTRAINT invites_created_by_user_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: invites invites_used_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invites
    ADD CONSTRAINT invites_used_by_user_id_fkey FOREIGN KEY (used_by_user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: item_component_states item_component_states_item_instance_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_component_states
    ADD CONSTRAINT item_component_states_item_instance_id_fkey FOREIGN KEY (item_instance_id) REFERENCES public.item_instances(item_instance_id) ON DELETE CASCADE;


--
-- Name: item_instances item_instances_prototype_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_instances
    ADD CONSTRAINT item_instances_prototype_id_fkey FOREIGN KEY (prototype_id) REFERENCES public.item_prototypes(prototype_id) ON DELETE CASCADE;


--
-- Name: muting_rules muting_rules_created_by_user_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.muting_rules
    ADD CONSTRAINT muting_rules_created_by_user_fkey FOREIGN KEY (created_by_user) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: npc_relationships npc_relationships_npc_id_1_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.npc_relationships
    ADD CONSTRAINT npc_relationships_npc_id_1_fkey FOREIGN KEY (npc_id_1) REFERENCES public.npc_definitions(id) ON DELETE CASCADE;


--
-- Name: npc_relationships npc_relationships_npc_id_2_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.npc_relationships
    ADD CONSTRAINT npc_relationships_npc_id_2_fkey FOREIGN KEY (npc_id_2) REFERENCES public.npc_definitions(id) ON DELETE CASCADE;


--
-- Name: npc_spawn_rules npc_spawn_rules_npc_definition_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.npc_spawn_rules
    ADD CONSTRAINT npc_spawn_rules_npc_definition_id_fkey FOREIGN KEY (npc_definition_id) REFERENCES public.npc_definitions(id) ON DELETE CASCADE;


--
-- Name: player_inventories player_inventories_player_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.player_inventories
    ADD CONSTRAINT player_inventories_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(player_id) ON DELETE CASCADE;


--
-- Name: player_sanity player_sanity_player_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.player_sanity
    ADD CONSTRAINT player_sanity_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(player_id) ON DELETE CASCADE;


--
-- Name: players players_new_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.players
    ADD CONSTRAINT players_new_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: room_links room_links_from_room_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room_links
    ADD CONSTRAINT room_links_from_room_id_fkey FOREIGN KEY (from_room_id) REFERENCES public.rooms(id) ON DELETE CASCADE;


--
-- Name: room_links room_links_to_room_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room_links
    ADD CONSTRAINT room_links_to_room_id_fkey FOREIGN KEY (to_room_id) REFERENCES public.rooms(id) ON DELETE RESTRICT;


--
-- Name: rooms rooms_subzone_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT rooms_subzone_id_fkey FOREIGN KEY (subzone_id) REFERENCES public.subzones(id) ON DELETE CASCADE;


--
-- Name: sanity_adjustment_log sanity_adjustment_log_player_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sanity_adjustment_log
    ADD CONSTRAINT sanity_adjustment_log_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(player_id) ON DELETE CASCADE;


--
-- Name: sanity_cooldowns sanity_cooldowns_player_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sanity_cooldowns
    ADD CONSTRAINT sanity_cooldowns_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(player_id) ON DELETE CASCADE;


--
-- Name: sanity_exposure_state sanity_exposure_state_player_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sanity_exposure_state
    ADD CONSTRAINT sanity_exposure_state_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(player_id) ON DELETE CASCADE;


--
-- Name: subzones subzones_zone_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subzones
    ADD CONSTRAINT subzones_zone_id_fkey FOREIGN KEY (zone_id) REFERENCES public.zones(id) ON DELETE CASCADE;


--
-- Name: zone_configurations zone_configurations_subzone_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.zone_configurations
    ADD CONSTRAINT zone_configurations_subzone_id_fkey FOREIGN KEY (subzone_id) REFERENCES public.subzones(id) ON DELETE CASCADE;


--
-- Name: zone_configurations zone_configurations_zone_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.zone_configurations
    ADD CONSTRAINT zone_configurations_zone_id_fkey FOREIGN KEY (zone_id) REFERENCES public.zones(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict 9wgDAUNpT1eOAIH0i0DMbSjMLNdwKmkdYM53riAlkOJhGZGapfJkElb4oTIl4Ef
