#!/usr/bin/env pwsh
# Apply arena zone (limbo/arena) migration to target databases.
#
# This script:
# - Uses .env.local (or .env) when targeting mythos_dev; .env.unit_test for mythos_unit/mythos_e2e.
# - Applies per-environment arena migrations (generated by scripts/gen_arena_migration_sql.py).

[Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidUsingWriteHost', '', Justification = 'Status messages use Write-Host for clarity')]
param(
    [string[]]$TargetDbs = @("mythos_unit", "mythos_e2e")
)

$ErrorActionPreference = "Stop"

Write-Host "Applying arena zone migration to target databases" -ForegroundColor Green
Write-Host "==================================================" -ForegroundColor Green
Write-Host ""

$ProjectRoot = Split-Path $PSScriptRoot -Parent

# Resolve env file: mythos_dev -> .env.local or .env; test dbs -> .env.unit_test
$envPath = $null
$targetsDev = $TargetDbs | Where-Object { $_ -eq "mythos_dev" }
$targetsTest = $TargetDbs | Where-Object { $_ -match "mythos_unit|mythos_e2e" }
if ($targetsDev.Count -gt 0 -and (Test-Path (Join-Path $ProjectRoot ".env.local"))) {
    $envPath = Join-Path $ProjectRoot ".env.local"
}
elseif ($targetsDev.Count -gt 0 -and (Test-Path (Join-Path $ProjectRoot ".env"))) {
    $envPath = Join-Path $ProjectRoot ".env"
}
elseif ($targetsTest.Count -gt 0 -and (Test-Path (Join-Path $ProjectRoot ".env.unit_test"))) {
    $envPath = Join-Path $ProjectRoot ".env.unit_test"
}
elseif (Test-Path (Join-Path $ProjectRoot ".env.local")) {
    $envPath = Join-Path $ProjectRoot ".env.local"
}
elseif (Test-Path (Join-Path $ProjectRoot ".env.unit_test")) {
    $envPath = Join-Path $ProjectRoot ".env.unit_test"
}
elseif (Test-Path (Join-Path $ProjectRoot ".env")) {
    $envPath = Join-Path $ProjectRoot ".env"
}

if (-not $envPath) {
    Write-Host "[ERROR] No env file found. For mythos_dev use .env.local or .env; for test dbs use .env.unit_test." -ForegroundColor Red
    exit 1
}

Write-Host "[INFO] Loading configuration from $envPath" -ForegroundColor Cyan
$envContent = Get-Content $envPath -Raw

$databaseUrl = ""
if ($envContent -match 'DATABASE_URL=(.+)') {
    $databaseUrl = $matches[1].Trim()
}
else {
    Write-Host "[ERROR] DATABASE_URL not found in $envPath" -ForegroundColor Red
    exit 1
}

if ($databaseUrl -notmatch 'postgresql\+?asyncpg?://([^:]+):([^@]+)@([^:]+):(\d+)/(.+)') {
    Write-Host "[ERROR] Invalid PostgreSQL URL format: $databaseUrl" -ForegroundColor Red
    exit 1
}

$dbUser = $matches[1]
$dbPassword = $matches[2]
$dbHost = $matches[3]
$dbPort = $matches[4]

Write-Host "Database Configuration (from $envPath):" -ForegroundColor Yellow
Write-Host "  Host: $dbHost" -ForegroundColor Gray
Write-Host "  Port: $dbPort" -ForegroundColor Gray
Write-Host "  User: $dbUser" -ForegroundColor Gray
Write-Host ""

$psqlPath = Get-Command psql -ErrorAction SilentlyContinue
if (-not $psqlPath) {
    $commonPaths = @(
        "C:\Program Files\PostgreSQL\*\bin\psql.exe",
        "C:\Program Files (x86)\PostgreSQL\*\bin\psql.exe"
    )

    $found = $false
    foreach ($path in $commonPaths) {
        $psqlFiles = Get-ChildItem -Path $path -ErrorAction SilentlyContinue
        if ($psqlFiles) {
            $psqlPath = $psqlFiles[0].FullName
            $found = $true
            break
        }
    }

    if (-not $found) {
        Write-Host "[ERROR] PostgreSQL client (psql) not found" -ForegroundColor Red
        Write-Host "[SOLUTION] Install PostgreSQL from: https://www.postgresql.org/download/windows/" -ForegroundColor Yellow
        exit 1
    }
}
else {
    $psqlPath = $psqlPath.Path
}

Write-Host "[INFO] Using psql: $psqlPath" -ForegroundColor Cyan
Write-Host ""

$env:PGPASSWORD = $dbPassword

$constraintMigrationFile = Join-Path -Path $ProjectRoot -ChildPath "db\migrations\20260227_add_arena_zone_type_constraint.sql"
if (-not (Test-Path $constraintMigrationFile)) {
    Write-Host "[ERROR] Arena schema migration not found: $constraintMigrationFile" -ForegroundColor Red
    exit 1
}

try {
    foreach ($targetDb in $TargetDbs) {
        $migrationFile = $null

        switch ($targetDb) {
            "mythos_unit" {
                $migrationFile = Join-Path -Path $ProjectRoot -ChildPath "data\db\migrations\20260227_add_arena_zone_unit.sql"
            }
            "mythos_e2e" {
                $migrationFile = Join-Path -Path $ProjectRoot -ChildPath "data\db\migrations\20260227_add_arena_zone_e2e.sql"
            }
            "mythos_dev" {
                $migrationFile = Join-Path -Path $ProjectRoot -ChildPath "data\db\migrations\20260227_add_arena_zone_dev.sql"
            }
            default {
                Write-Host "[WARNING] No arena migration configured for database '$targetDb'; skipping." -ForegroundColor Yellow
                continue
            }
        }

        if (-not (Test-Path $migrationFile)) {
            Write-Host "[ERROR] Migration file not found for '$targetDb': $migrationFile" -ForegroundColor Red
            Write-Host "[SOLUTION] Run: python scripts/gen_arena_migration_sql.py" -ForegroundColor Yellow
            exit 1
        }

        # 1. Apply schema migration: add 'arena' to zones.zone_type CHECK (so DML can insert arena zone)
        Write-Host "Applying arena zone_type schema migration to '$targetDb' ..." -ForegroundColor Yellow
        $schemaSql = "SET search_path TO $targetDb;`n" + (Get-Content $constraintMigrationFile -Raw)
        $schemaResult = $schemaSql | & $psqlPath -h $dbHost -p $dbPort -U $dbUser -d $targetDb -v ON_ERROR_STOP=1 2>&1
        if ($LASTEXITCODE -ne 0) {
            Write-Host "[ERROR] Arena schema migration failed for '$targetDb':" -ForegroundColor Red
            Write-Host $schemaResult -ForegroundColor Red
            exit 1
        }
        Write-Host "[OK] Arena schema migration applied to '$targetDb'" -ForegroundColor Green

        # 2. Apply arena DML migration (zones, subzones, rooms, room_links, zone_config)
        Write-Host "Applying arena zone DML migration to database '$targetDb' using $migrationFile ..." -ForegroundColor Yellow

        $result = & $psqlPath -h $dbHost -p $dbPort -U $dbUser -d $targetDb -v ON_ERROR_STOP=1 -f $migrationFile 2>&1

        if ($LASTEXITCODE -eq 0) {
            Write-Host "[OK] Migration applied successfully to '$targetDb'" -ForegroundColor Green
        }
        else {
            Write-Host "[ERROR] Failed to apply migration to '$targetDb':" -ForegroundColor Red
            Write-Host $result -ForegroundColor Red
            exit 1
        }

        Write-Host ""
    }

    Write-Host "Arena zone migration applied to all target databases." -ForegroundColor Green
}
finally {
    Remove-Item Env:\PGPASSWORD -ErrorAction SilentlyContinue
}
