"""Generate the #829 Arkham street-grid migration for existing databases.

The base DML files already carry the rebuilt city, but a database that was loaded
before #829 still holds the old 117-room Arkham. Reloading the world seed would fix
that and destroy every player row with it, so - following `data/db/migrations/README.md`
- this emits idempotent SQL that brings an existing database up to date in place.

Diffed against a baseline git ref rather than hand-listed, so the migration cannot drift
from the DML it is derived from.

What the migration does, per environment:

1. deletes the Arkham street rooms the rebuild replaced (``room_links`` rows cascade)
2. inserts the five landmark sub-zones and their ``zone_configurations`` mappings
3. upserts every Arkham room, which also carries the authored map coordinates
4. upserts every ``room_links`` row touching an Arkham room, including the Innsmouth
   causeway pair, whose Arkham endpoint is deleted and recreated in step 1/3
5. rehouses the seven NPCs whose rooms were replaced, and their spawn rules

    python scripts/gen_arkham_grid_migration.py --baseline a77fb9a
"""

from __future__ import annotations

import argparse
import re
import subprocess
from pathlib import Path

ENVS = ("dev", "unit", "e2e")
ARKHAM = "earth_arkhamcity_"
NULL = "\\N"
TERMINATOR = "\n\\."
MIGRATION = "data/db/migrations/20260913_arkham_street_grid_{env}.sql"

# NPCs whose rooms the rebuild replaced. Mirrors NPC_REHOMING in splice_arkham_grid.py.
NPC_REHOMING: dict[str, tuple[str, str]] = {
    "51": ("merchant", "earth_arkhamcity_merchant_intersection_peabody_pickman"),
    "52": ("frenchhill", "earth_arkhamcity_frenchhill_intersection_frenchhill_pickman"),
    "53": ("campus", "earth_arkhamcity_campus_intersection_college_garrison"),
    "55": ("campus", "earth_arkhamcity_campus_room_college_st_002"),
    "57": ("independence_square", "earth_arkhamcity_independence_square_room_square_001"),
    "58": ("downtown", "earth_arkhamcity_downtown_room_lich_st_001"),
    "60": ("hangmans_hill", "earth_arkhamcity_hangmans_hill_room_summit_001"),
}


def copy_block(text: str, table: str) -> list[list[str]]:
    m = re.search(rf"^COPY [\w.]+\.{table} \([^)]*\) FROM stdin;\n", text, re.M)
    if not m:
        raise SystemExit(f"no COPY block for {table}")
    end = text.index(TERMINATOR, m.end())
    return [line.split("\t") for line in text[m.end() : end + 1].rstrip("\n").split("\n")]


def lit(value: str) -> str:
    """A pg_dump COPY field as a SQL literal."""
    if value == NULL:
        return "NULL"
    return "'" + value.replace("'", "''") + "'"


def num(value: str) -> str:
    return "NULL" if value == NULL else value


def boolean(value: str) -> str:
    return "TRUE" if value == "t" else "FALSE"


def baseline_dml(ref: str, env: str) -> str:
    out = subprocess.run(
        ["git", "-C", "data", "show", f"{ref}:db/mythos_{env}_dml.sql"],
        capture_output=True,
        text=True,
        encoding="utf-8",
        check=False,
    )
    if out.returncode != 0 or not out.stdout:
        raise SystemExit(f"cannot read baseline {ref}:db/mythos_{env}_dml.sql -- {out.stderr.strip()}")
    return out.stdout


def build(env: str, ref: str) -> str:
    schema = f"mythos_{env}"
    current = Path(f"data/db/mythos_{env}_dml.sql").read_bytes().decode("utf-8")
    before = baseline_dml(ref, env)

    old_rooms = {r[2] for r in copy_block(before, "rooms") if r[2].startswith(ARKHAM)}
    rooms = [r for r in copy_block(current, "rooms") if r[2].startswith(ARKHAM)]
    new_ids = {r[2] for r in rooms}
    removed = sorted(old_rooms - new_ids)

    arkham_uuids = {r[0] for r in rooms}
    links = [x for x in copy_block(current, "room_links") if x[1] in arkham_uuids or x[2] in arkham_uuids]

    zone_uuid = next(z[0] for z in copy_block(current, "zones") if z[1] == "earth/arkhamcity")
    old_subzones = {s[0] for s in copy_block(before, "subzones")}
    subzones = [s for s in copy_block(current, "subzones") if s[1] == zone_uuid and s[0] not in old_subzones]
    old_cfgs = {c[0] for c in copy_block(before, "zone_configurations")}
    configs = [c for c in copy_block(current, "zone_configurations") if c[0] not in old_cfgs]

    out: list[str] = [
        f"-- #829: rebuild the Arkham street grid from the canonical map plate ({schema}).",
        "--",
        "-- Idempotent and non-destructive: brings a database loaded before #829 up to the",
        "-- current base DML without touching players, items, or quest state. Safe to re-run.",
        "--",
        f"-- Generated by scripts/gen_arkham_grid_migration.py --baseline {ref}",
        "-- Do not hand-edit; regenerate instead.",
        "",
        "BEGIN;",
        f"SET search_path TO {schema};",
        "",
        "-- 1. Clear every exit touching Arkham. This MUST precede the room delete:",
        "--    room_links.from_room_id is ON DELETE CASCADE but to_room_id is ON DELETE",
        "--    RESTRICT, so a room that anything still leads to cannot be removed.",
        "--",
        "--    It also prevents a subtler problem. Rooms whose stable_id survived the",
        "--    rebuild keep their UUID and are upserted rather than deleted, so their OLD",
        "--    exits are never cascaded away; an exit in a direction the room no longer has",
        "--    would survive as a stale link between two surviving rooms. Clearing first",
        "--    makes the result converge regardless of what the database held before.",
        "DELETE FROM room_links",
        " WHERE from_room_id IN (SELECT id FROM rooms WHERE stable_id LIKE 'earth\\_arkhamcity\\_%')",
        "    OR to_room_id   IN (SELECT id FROM rooms WHERE stable_id LIKE 'earth\\_arkhamcity\\_%');",
        "",
        f"-- 2. Remove the {len(removed)} street rooms the rebuild replaced outright.",
    ]
    if removed:
        values = ",\n    ".join(lit(s) for s in removed)
        out += [f"DELETE FROM rooms WHERE stable_id IN (\n    {values}\n);", ""]
    else:
        out += ["-- (none: baseline already matches)", ""]

    out += ["-- 3. The five single-room landmark sub-zones."]
    if subzones:
        rows = ",\n    ".join(
            f"({lit(s[0])}::uuid, {lit(s[1])}::uuid, {lit(s[2])}, {lit(s[3])}, {lit(s[4])}, "
            f"{lit(s[5])}, {lit(s[6])}::jsonb)"
            for s in subzones
        )
        out += [
            "INSERT INTO subzones (id, zone_id, stable_id, name, environment, description, special_rules)",
            f"VALUES\n    {rows}",
            "ON CONFLICT (id) DO NOTHING;",
            "",
        ]
    else:
        out += ["-- (already present)", ""]

    out += ["-- 4. Their NPC zone-configuration mappings."]
    if configs:
        rows = ",\n    ".join(f"({lit(c[0])}::uuid, {lit(c[1])}::uuid, {lit(c[2])}::uuid)" for c in configs)
        out += [
            "INSERT INTO zone_configurations (id, zone_id, subzone_id)",
            f"VALUES\n    {rows}",
            "ON CONFLICT (zone_id, subzone_id) DO NOTHING;",
            "",
        ]
    else:
        out += ["-- (already present)", ""]

    out += [
        f"-- 5. Every Arkham room ({len(rooms)}), carrying the authored map coordinates.",
        "--    ON CONFLICT so a partially-migrated database converges rather than erroring.",
        "INSERT INTO rooms (id, subzone_id, stable_id, name, description, attributes,",
        "                   map_x, map_y, map_origin_zone, map_symbol, map_style)",
        "VALUES",
    ]
    out.append(
        ",\n".join(
            f"    ({lit(r[0])}::uuid, {lit(r[1])}::uuid, {lit(r[2])}, {lit(r[3])}, {lit(r[4])}, "
            f"{lit(r[5])}::jsonb, {num(r[6])}, {num(r[7])}, {boolean(r[8])}, {lit(r[9])}, {lit(r[10])})"
            for r in rooms
        )
    )
    out += [
        "ON CONFLICT (id) DO UPDATE SET",
        "    subzone_id = EXCLUDED.subzone_id,",
        "    stable_id = EXCLUDED.stable_id,",
        "    name = EXCLUDED.name,",
        "    description = EXCLUDED.description,",
        "    attributes = EXCLUDED.attributes,",
        "    map_x = EXCLUDED.map_x,",
        "    map_y = EXCLUDED.map_y,",
        "    map_origin_zone = EXCLUDED.map_origin_zone,",
        "    map_symbol = EXCLUDED.map_symbol,",
        "    map_style = EXCLUDED.map_style;",
        "",
        f"-- 6. Every exit touching an Arkham room ({len(links)}).",
        "INSERT INTO room_links (id, from_room_id, to_room_id, direction, attributes)",
        "VALUES",
    ]
    out.append(
        ",\n".join(
            f"    ({lit(x[0])}::uuid, {lit(x[1])}::uuid, {lit(x[2])}::uuid, {lit(x[3])}, {lit(x[4])}::jsonb)"
            for x in links
        )
    )
    out += [
        "ON CONFLICT (id) DO UPDATE SET",
        "    from_room_id = EXCLUDED.from_room_id,",
        "    to_room_id = EXCLUDED.to_room_id,",
        "    direction = EXCLUDED.direction,",
        "    attributes = EXCLUDED.attributes;",
        "",
        "-- 7. Widen npc_definitions.room_id before rehoming anyone into it.",
        "--    It is character varying(50), while containers.room_id and",
        "--    players.current_room_id are both varchar(255). 200 of the 518 rebuilt Arkham",
        "--    room ids are longer than 50 characters (the longest,",
        "--    earth_arkhamcity_lowersouthside_intersection_parsonage_saltonstall, is 66), so",
        "--    at the old width those rooms simply could not host an NPC. Widening a varchar",
        "--    needs no table rewrite.",
        "ALTER TABLE npc_definitions ALTER COLUMN room_id TYPE character varying(255);",
        "",
        "-- 8. Rehouse the NPCs whose rooms were replaced, and their spawn rules.",
    ]
    for npc_id, (subzone, room) in sorted(NPC_REHOMING.items(), key=lambda kv: int(kv[0])):
        out.append(
            f"UPDATE npc_definitions SET sub_zone_id = {lit(subzone)}, room_id = {lit(room)} "
            f"WHERE id = {npc_id};"
        )
    out.append("")
    for npc_id, (subzone, _room) in sorted(NPC_REHOMING.items(), key=lambda kv: int(kv[0])):
        out.append(
            f"UPDATE npc_spawn_rules SET sub_zone_id = {lit(subzone)} WHERE npc_definition_id = {npc_id};"
        )

    out += ["", "COMMIT;", ""]
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--baseline", default="a77fb9a", help="git ref in data/ before #829")
    args = parser.parse_args()

    for env in ENVS:
        sql = build(env, args.baseline)
        path = Path(MIGRATION.format(env=env))
        path.write_bytes(sql.encode("utf-8"))
        print(f"{path}  ({len(sql.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
