# Generate authoritative database schema from mythos_dev PostgreSQL database
# This script extracts DDL from the mythos_dev database and writes it to db/authoritative_schema.sql

param(
    [string]$DB_HOST = "localhost",
    [string]$DB_USER = "postgres",
    [string]$DB_NAME = "mythos_dev",
    [string]$DB_PASSWORD = "",
    [string]$OUTPUT_FILE = "db/authoritative_schema.sql"
)

$ErrorActionPreference = "Stop"

function Write-ColorOutput {
    param(
        [string]$Message,
        [string]$Color = "White"
    )
    Write-Host $Message -ForegroundColor $Color
}

Write-ColorOutput "Generating authoritative schema from $DB_NAME..." "Green"

# Check if pg_dump is available
$pgDumpPath = Get-Command pg_dump -ErrorAction SilentlyContinue
if (-not $pgDumpPath) {
    Write-ColorOutput "Error: pg_dump is not installed or not in PATH" "Red"
    exit 1
}

# Check if database is accessible (optional check)
$pgIsReadyPath = Get-Command pg_isready -ErrorAction SilentlyContinue
if ($pgIsReadyPath) {
    $env:PGPASSWORD = $DB_PASSWORD
    $isReady = & pg_isready -h $DB_HOST -U $DB_USER -d $DB_NAME 2>&1
    if ($LASTEXITCODE -ne 0) {
        Write-ColorOutput "Warning: Cannot verify database connectivity. Proceeding anyway..." "Yellow"
    }
}

# Create output directory if it doesn't exist
$outputDir = Split-Path -Parent $OUTPUT_FILE
if (-not (Test-Path $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
}

# Generate schema dump
Write-ColorOutput "Running pg_dump..." "Green"

$env:PGPASSWORD = $DB_PASSWORD

& pg_dump -h $DB_HOST -U $DB_USER -d $DB_NAME `
    --schema-only `
    --no-owner `
    --no-privileges `
    --clean `
    --if-exists `
    --file=$OUTPUT_FILE

if ($LASTEXITCODE -ne 0) {
    Write-ColorOutput "Error: pg_dump failed" "Red"
    exit 1
}

# Add header comment to the generated file
$headerComment = @"
-- Authoritative Database Schema
-- Generated from: $DB_NAME database
-- Generated on: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss UTC")
-- Generated by: scripts/generate_schema_from_dev.ps1
--
-- This file is the authoritative source of truth for the database schema.
-- It is generated directly from the mythos_dev database using pg_dump.
--
-- To regenerate this file:
--   1. Make schema changes in the mythos_dev database
--   2. Run: .\scripts\generate_schema_from_dev.ps1
--   3. Review the changes
--   4. Commit the updated file to git
--
-- SET statements for clean execution
SET client_min_messages = WARNING;
SET search_path = public;

"@

# Prepend header to the file
$tempFile = [System.IO.Path]::GetTempFileName()
$headerComment | Out-File -FilePath $tempFile -Encoding utf8 -NoNewline
Get-Content $OUTPUT_FILE -Raw | Add-Content -Path $tempFile
Move-Item -Path $tempFile -Destination $OUTPUT_FILE -Force

Write-ColorOutput "Schema generated successfully: $OUTPUT_FILE" "Green"
Write-ColorOutput "Please review the generated file before committing." "Yellow"
