#!/bin/bash
# Generate environment DDL from mythos_dev PostgreSQL database
# This script extracts DDL from the mythos_dev database and writes it to db/mythos_dev_ddl.sql

set -euo pipefail

# Configuration
DB_HOST="${DB_HOST:-localhost}"
DB_USER="${DB_USER:-postgres}"
DB_NAME="${DB_NAME:-mythos_dev}"
OUTPUT_FILE="${OUTPUT_FILE:-db/mythos_dev_ddl.sql}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}Generating DDL from ${DB_NAME}...${NC}"

# Check if pg_dump is available
if ! command -v pg_dump &> /dev/null; then
    echo -e "${RED}Error: pg_dump is not installed or not in PATH${NC}"
    exit 1
fi

# Check if database is accessible
if ! PGPASSWORD="${DB_PASSWORD:-}" pg_isready -h "${DB_HOST}" -U "${DB_USER}" -d "${DB_NAME}" &> /dev/null; then
    echo -e "${YELLOW}Warning: Cannot verify database connectivity. Proceeding anyway...${NC}"
fi

# Create output directory if it doesn't exist
mkdir -p "$(dirname "${OUTPUT_FILE}")"

# Generate schema dump
# --schema-only: Only dump schema, no data
# --no-owner: Don't output commands to set ownership of objects
# --no-privileges: Don't output commands to set privileges
# --clean: Include commands to drop objects before creating them
# --if-exists: Use IF EXISTS when dropping objects
echo -e "${GREEN}Running pg_dump...${NC}"

if [ -n "${DB_PASSWORD:-}" ]; then
    export PGPASSWORD="${DB_PASSWORD}"
fi

pg_dump -h "${DB_HOST}" -U "${DB_USER}" -d "${DB_NAME}" \
    --schema-only \
    --no-owner \
    --no-privileges \
    --clean \
    --if-exists \
    --file="${OUTPUT_FILE}"

# Add header comment to the generated file
HEADER_COMMENT="-- Environment DDL (${DB_NAME})
-- Generated from: ${DB_NAME} database
-- Generated on: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
-- Generated by: scripts/generate_schema_from_dev.sh
--
-- This file is the DDL for the ${DB_NAME} environment. It is generated using pg_dump.
--
-- To regenerate: make schema changes in ${DB_NAME}, then run ./scripts/generate_schema_from_dev.sh
--
-- SET statements for clean execution
SET client_min_messages = WARNING;

"

# Prepend header to the file
TEMP_FILE=$(mktemp)
echo -n "${HEADER_COMMENT}" > "${TEMP_FILE}"
cat "${OUTPUT_FILE}" >> "${TEMP_FILE}"
mv "${TEMP_FILE}" "${OUTPUT_FILE}"

echo -e "${GREEN}Schema generated successfully: ${OUTPUT_FILE}${NC}"
echo -e "${YELLOW}Please review the generated file before committing.${NC}"
