from typing import Any, NoReturn

def create_error_context(*args: Any, **kwargs: Any) -> Any: ...
def log_and_raise_enhanced(*args: Any, **kwargs: Any) -> NoReturn: ...
def log_and_raise_http_enhanced(*args: Any, **kwargs: Any) -> NoReturn: ...
def log_structured_error(*args: Any, **kwargs: Any) -> None: ...
def wrap_third_party_exception_enhanced(*args: Any, **kwargs: Any) -> NoReturn: ...
def create_enhanced_error_context(*args: Any, **kwargs: Any) -> Any: ...
def log_performance_metric(*args: Any, **kwargs: Any) -> None: ...
def log_security_event_enhanced(*args: Any, **kwargs: Any) -> None: ...
