from typing import Any, NoReturn

def create_error_context(*args: Any, **kwargs: Any) -> Any: ...


def create_context_from_request(*args: Any, **kwargs: Any) -> Any: ...


def create_context_from_websocket(*args: Any, **kwargs: Any) -> Any: ...


def log_and_raise(*args: Any, **kwargs: Any) -> NoReturn: ...


def log_and_raise_http(*args: Any, **kwargs: Any) -> NoReturn: ...
